using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EnemizerLibrary
{
    public static class RoomIdConstants
    {
        public static string GetRoomName(int roomId)
        {
            string roomName;

            if (roomNames.TryGetValue(roomId, out roomName))
            {
                return roomName;
            }

            return null;
        }

        public static Dictionary<int, string> roomNames = new Dictionary<int, string>()
        {
            { R0_Ganon, "Ganon" },
            { R1_HyruleCastle_NorthCorridor, "Hyrule Castle (North Corridor)" },
            { R2_HyruleCastle_SwitchRoom, "Hyrule Castle (Switch Room)" },
            { R3_HoulihanRoom, "Houlihan Room" },
            { R4_TurtleRock_CrystalRollerRoom, "Turtle Rock (Crysta-roller Room)" },
            { R5_EmptyCloneRoom0x05, "Empty Clone Room" },
            { R6_SwampPalace_Arrghus, "Swamp Palace (Arrghus[Boss])" },
            { R7_TowerofHera_Moldorm, "Tower of Hera (Moldorm[Boss])" },
            { R8_Cave_HealingFairy, "Cave (Healing Fairy)" },
            { R9_PalaceofDarkness0x09, "Palace of Darkness" },
            { R10_PalaceofDarkness_StalfosTrapRoom, "Palace of Darkness (Stalfos Trap Room)" },
            { R11_PalaceofDarkness_TurtleRoom, "Palace of Darkness (Turtle Room)" },
            { R12_GanonsTower_EntranceRoom, "Ganon's Tower (Entrance Room)" },
            { R13_GanonsTower_Agahnim2, "Ganon's Tower (Agahnim2[Boss])" },
            { R14_IcePalace_EntranceRoom, "Ice Palace (Entrance Room)" },
            { R15_EmptyCloneRoom0x0F, "Empty Clone Room" },
            { R16_GanonEvacuationRoute, "Ganon Evacuation Route" },
            { R17_HyruleCastle_BombableStockRoom, "Hyrule Castle (Bombable Stock Room)" },
            { R18_Sanctuary, "Sanctuary" },
            { R19_TurtleRock_Hokku_BokkuKeyRoom2, "Turtle Rock (Hokku-Bokku Key Room 2)" },
            { R20_TurtleRock_BigKeyRoom, "Turtle Rock (Big Key Room)" },
            { R21_TurtleRock0x15, "Turtle Rock" },
            { R22_SwampPalace_SwimmingTreadmill, "Swamp Palace (Swimming Treadmill)" },
            { R23_TowerofHera_MoldormFallRoom, "Tower of Hera (Moldorm Fall Room)" },
            { R24_Cave0x18_BigFairyDropEntrance, "Big Fairy Drop Entrance Cave" },
            { R25_PalaceofDarkness_DarkMaze, "Palace of Darkness (Dark Maze)" },
            { R26_PalaceofDarkness_BigChestRoom, "Palace of Darkness (Big Chest Room)" },
            { R27_PalaceofDarkness_Mimics_MovingWallRoom, "Palace of Darkness (Mimics / Moving Wall Room)" },
            { R28_GanonsTower_IceArmos, "Ganon's Tower (Ice Armos)" },
            { R29_GanonsTower_FinalHallway, "Ganon's Tower (Final Hallway)" },
            { R30_IcePalace_BombFloor_BariRoom, "Ice Palace (Bomb Floor / Bari Room)" },
            { R31_IcePalace_Pengator_BigKeyRoom, "Ice Palace (Pengator / Big Key Room)" },
            { R32_AgahnimsTower_Agahnim, "Agahnim's Tower (Agahnim[Boss])" },
            { R33_HyruleCastle_KeyRatRoom, "Hyrule Castle (Key-rat Room)" },
            { R34_HyruleCastle_SewerTextTriggerRoom, "Hyrule Castle (Sewer Text Trigger Room)" },
            { R35_TurtleRock_WestExittoBalcony, "Turtle Rock (West Exit to Balcony)" },
            { R36_TurtleRock_DoubleHokku_Bokku_BigchestRoom, "Turtle Rock (Double Hokku-Bokku / Big chest Room)" },
            { R37_EmptyCloneRoom0x25, "Empty Clone Room" },
            { R38_SwampPalace_StatueRoom, "Swamp Palace (Statue Room)" },
            { R39_TowerofHera_BigChest, "Tower of Hera (Big Chest)" },
            { R40_SwampPalace_EntranceRoom, "Swamp Palace (Entrance Room)" },
            { R41_SkullWoods_Mothula, "Skull Woods (Mothula[Boss])" },
            { R42_PalaceofDarkness_BigHubRoom, "Palace of Darkness (Big Hub Room)" },
            { R43_PalaceofDarkness_MapChest_FairyRoom, "Palace of Darkness (Map Chest / Fairy Room)" },
            { R44_Cave0x2C_HookshotCaveBackdoor, "Hookshot Cave Backdoor (Big Fairy)" },
            { R45_EmptyCloneRoom0x2D, "Empty Clone Room" },
            { R46_IcePalace_CompassRoom, "Ice Palace (Compass Room)" },
            { R47_Cave_KakarikoWellHP, "Cave (Kakariko Well HP)" },
            { R48_AgahnimsTower_MaidenSacrificeChamber, "Agahnim's Tower (Maiden Sacrifice Chamber)" },
            { R49_TowerofHera_HardhatBeetlesRoom, "Tower of Hera (Hardhat Beetles Room)" },
            { R50_HyruleCastle_SewerKeyChestRoom, "Hyrule Castle (Sewer Key Chest Room)" },
            { R51_DesertPalace_Lanmolas, "Desert Palace (Lanmolas[Boss])" },
            { R52_SwampPalace_PushBlockPuzzle_Pre_BigKeyRoom, "Swamp Palace (Push Block Puzzle / Pre-Big Key Room)" },
            { R53_SwampPalace_BigKey_BSRoom, "Swamp Palace (Big Key / BS Room)" },
            { R54_SwampPalace_BigChestRoom, "Swamp Palace (Big Chest Room)" },
            { R55_SwampPalace_MapChest_WaterFillRoom, "Swamp Palace (Map Chest / Water Fill Room)" },
            { R56_SwampPalace_KeyPotRoom, "Swamp Palace (Key Pot Room)" },
            { R57_SkullWoods_GibdoKey_MothulaHoleRoom, "Skull Woods (Gibdo Key / Mothula Hole Room)" },
            { R58_PalaceofDarkness_BombableFloorRoom, "Palace of Darkness (Bombable Floor Room)" },
            { R59_PalaceofDarkness_SpikeBlock_ConveyorRoom, "Palace of Darkness (Spike Block / Conveyor Room)" },
            { R60_Cave0x3C_HookshotCave, "Hookshot Cave" },
            { R61_GanonsTower_TorchRoom2, "Ganon's Tower (Torch Room 2)" },
            { R62_IcePalace_StalfosKnights_ConveyorHellway, "Ice Palace (Stalfos Knights / Conveyor Hellway)" },
            { R63_IcePalace_MapChestRoom, "Ice Palace (Map Chest Room)" },
            { R64_AgahnimsTower_FinalBridgeRoom, "Agahnim's Tower (Final Bridge Room)" },
            { R65_HyruleCastle_FirstDarkRoom, "Hyrule Castle (First Dark Room)" },
            { R66_HyruleCastle_6RopesRoom, "Hyrule Castle (6 Ropes Room)" },
            { R67_DesertPalace_TorchPuzzle_MovingWallRoom, "Desert Palace (Torch Puzzle / Moving Wall Room)" },
            { R68_ThievesTown_BigChestRoom, "Thieves Town (Big Chest Room)" },
            { R69_ThievesTown_JailCellsRoom, "Thieves Town (Jail Cells Room)" },
            { R70_SwampPalace_CompassChestRoom, "Swamp Palace (Compass Chest Room)" },
            { R71_EmptyCloneRoom0x47, "Empty Clone Room" },
            { R72_EmptyCloneRoom0x48, "Empty Clone Room" },
            { R73_SkullWoods_GibdoTorchPuzzleRoom, "Skull Woods (Gibdo Torch Puzzle Room)" },
            { R74_PalaceofDarkness_EntranceRoom, "Palace of Darkness (Entrance Room)" },
            { R75_PalaceofDarkness_Warps_SouthMimicsRoom, "Palace of Darkness (Warps / South Mimics Room)" },
            { R76_GanonsTower_Mini_HelmasaurConveyorRoom, "Ganon's Tower (Mini-Helmasaur Conveyor Room)" },
            { R77_GanonsTower_MoldormRoom, "Ganon's Tower (Moldorm Room)" },
            { R78_IcePalace_Bomb_JumpRoom, "Ice Palace (Bomb-Jump Room)" },
            { R79_IcePalaceCloneRoom_FairyRoom, "Ice Palace Clone Room (Fairy Room)" },
            { R80_HyruleCastle_WestCorridor, "Hyrule Castle (West Corridor)" },
            { R81_HyruleCastle_ThroneRoom, "Hyrule Castle (Throne Room)" },
            { R82_HyruleCastle_EastCorridor, "Hyrule Castle (East Corridor)" },
            { R83_DesertPalace_Popos2_BeamosHellwayRoom, "Desert Palace (Popos 2 / Beamos Hellway Room)" },
            { R84_SwampPalace_UpstairsPitsRoom, "Swamp Palace (Upstairs Pits Room)" },
            { R85_CastleSecretEntrance_UncleDeathRoom, "Castle Secret Entrance / Uncle Death Room" },
            { R86_SkullWoods_KeyPot_TrapRoom, "Skull Woods (Key Pot / Trap Room)" },
            { R87_SkullWoods_BigKeyRoom, "Skull Woods (Big Key Room)" },
            { R88_SkullWoods_BigChestRoom, "Skull Woods (Big Chest Room)" },
            { R89_SkullWoods_FinalSectionEntranceRoom, "Skull Woods (Final Section Entrance Room)" },
            { R90_PalaceofDarkness_HelmasaurKing, "Palace of Darkness (Helmasaur King[Boss])" },
            { R91_GanonsTower_SpikePitRoom, "Ganon's Tower (Spike Pit Room)" },
            { R92_GanonsTower_Ganon_BallZ, "Ganon's Tower (Ganon-Ball Z)" },
            { R93_GanonsTower_Gauntlet1_2_3, "Ganon's Tower (Gauntlet 1/2/3)" },
            { R94_IcePalace_LonelyFirebar, "Ice Palace (Lonely Firebar)" },
            { R95_IcePalace_HiddenChest_SpikeFloorRoom, "Ice Palace (Hidden Chest / Spike Floor Room)" },
            { R96_HyruleCastle_WestEntranceRoom, "Hyrule Castle (West Entrance Room)" },
            { R97_HyruleCastle_MainEntranceRoom, "Hyrule Castle (Main Entrance Room)" },
            { R98_HyruleCastle_EastEntranceRoom, "Hyrule Castle (East Entrance Room)" },
            { R99_DesertPalace_FinalSectionEntranceRoom, "Desert Palace (Final Section Entrance Room)" },
            { R100_ThievesTown_WestAtticRoom, "Thieves Town (West Attic Room)" },
            { R101_ThievesTown_EastAtticRoom, "Thieves Town (East Attic Room)" },
            { R102_SwampPalace_HiddenChest_HiddenDoorRoom, "Swamp Palace (Hidden Chest / Hidden Door Room)" },
            { R103_SkullWoods_CompassChestRoom, "Skull Woods (Compass Chest Room)" },
            { R104_SkullWoods_KeyChest_TrapRoom, "Skull Woods (Key Chest / Trap Room)" },
            { R105_EmptyCloneRoom0x69, "Empty Clone Room" },
            { R106_PalaceofDarkness_RupeeRoom, "Palace of Darkness (Rupee Room)" },
            { R107_GanonsTower_MimicsRooms, "Ganon's Tower (Mimics Rooms)" },
            { R108_GanonsTower_LanmolasRoom, "Ganon's Tower (Lanmolas Room)" },
            { R109_GanonsTower_Gauntlet4_5, "Ganon's Tower (Gauntlet 4/5)" },
            { R110_IcePalace_PengatorsRoom, "Ice Palace (Pengators Room)" },
            { R111_EmptyCloneRoom0x6F, "Empty Clone Room" },
            { R112_HyruleCastle_SmallCorridortoJailCells, "Hyrule Castle (Small Corridor to Jail Cells)" },
            { R113_HyruleCastle_BoomerangChestRoom, "Hyrule Castle (Boomerang Chest Room)" },
            { R114_HyruleCastle_MapChestRoom, "Hyrule Castle (Map Chest Room)" },
            { R115_DesertPalace_BigChestRoom, "Desert Palace (Big Chest Room)" },
            { R116_DesertPalace_MapChestRoom, "Desert Palace (Map Chest Room)" },
            { R117_DesertPalace_BigKeyChestRoom, "Desert Palace (Big Key Chest Room)" },
            { R118_SwampPalace_WaterDrainRoom, "Swamp Palace (Water Drain Room)" },
            { R119_TowerofHera_EntranceRoom, "Tower of Hera (Entrance Room)" },
            { R120_EmptyCloneRoom0x78, "Empty Clone Room" },
            { R121_EmptyCloneRoom0x79, "Empty Clone Room" },
            { R122_EmptyCloneRoom0x7A, "Empty Clone Room" },
            { R123_GanonsTower, "Ganon's Tower (Sidways Conveyors / 4 Chest 4 Shooter / Square Pit)" },
            { R124_GanonsTower_EastSideCollapsingBridge_ExplodingWallRoom, "Ganon's Tower (East Side Collapsing Bridge / Exploding Wall Room)" },
            { R125_GanonsTower_Winder_WarpMazeRoom, "Ganon's Tower (Winder / Warp Maze Room)" },
            { R126_IcePalace_HiddenChest_BombableFloorRoom, "Ice Palace (Hidden Chest / Bombable Floor Room)" },
            { R127_IcePalace_BigSpikeTrapsRoom, "Ice Palace ( Big Spike Traps Room)" },
            { R128_HyruleCastle_JailCellRoom, "Hyrule Castle (Jail Cell Room)" },
            { R129_HyruleCastle_NextToChasmRoom, "Hyrule Castle (Next to Chasm Room)" },
            { R130_HyruleCastle_BasementChasmRoom, "Hyrule Castle (Basement Chasm Room)" },
            { R131_DesertPalace_WestEntranceRoom, "Desert Palace (West Entrance Room)" },
            { R132_DesertPalace_MainEntranceRoom, "Desert Palace (Main Entrance Room)" },
            { R133_DesertPalace_EastEntranceRoom, "Desert Palace (East Entrance Room)" },
            { R134_EmptyCloneRoom0x86, "Empty Clone Room" },
            { R135_TowerofHera_TileRoom, "Tower of Hera (Tile Room)" },
            { R136_EmptyCloneRoom0x88, "Empty Clone Room" },
            { R137_EasternPalace_FairyRoom, "Eastern Palace (Fairy Room)" },
            { R138_EmptyCloneRoom0x8A, "Empty Clone Room" },
            { R139_GanonsTower_BlockPuzzle_SpikeSkip_MapChestRoom, "Ganon's Tower (Block Puzzle / Spike Skip / Map Chest Room)" },
            { R140_GanonsTower_EastandWestDownstairs_BigChestRoom, "Ganon's Tower (East and West Downstairs / Big Chest Room)" },
            { R141_GanonsTower_Tile_TorchPuzzleRoom, "Ganon's Tower (Tile / Torch Puzzle Room)" },
            { R142_IcePalace0x8E, "Ice Palace (Blobs with Tetris Barrier)" },
            { R143_EmptyCloneRoom0x8F, "Empty Clone Room" },
            { R144_MiseryMire_Vitreous, "Misery Mire (Vitreous[Boss])" },
            { R145_MiseryMire_FinalSwitchRoom, "Misery Mire (Final Switch Room)" },
            { R146_MiseryMire_DarkBombWall_SwitchesRoom, "Misery Mire (Dark Bomb Wall / Switches Room)" },
            { R147_MiseryMire_DarkCaneFloorSwitchPuzzleRoom, "Misery Mire (Dark Cane Floor Switch Puzzle Room)" },
            { R148_EmptyCloneRoom0x94, "Empty Clone Room" },
            { R149_GanonsTower_FinalCollapsingBridgeRoom, "Ganon's Tower (Final Collapsing Bridge Room)" },
            { R150_GanonsTower_Torches1Room, "Ganon's Tower (Torches 1 Room)" },
            { R151_MiseryMire_TorchPuzzle_MovingWallRoom, "Misery Mire (Torch Puzzle / Moving Wall Room)" },
            { R152_MiseryMire_EntranceRoom, "Misery Mire (Entrance Room)" },
            { R153_EasternPalace_EyegoreKeyRoom, "Eastern Palace (Eyegore Key Room)" },
            { R154_EmptyCloneRoom0x9A, "Empty Clone Room" },
            { R155_GanonsTower_ManySpikes_WarpMazeRoom, "Ganon's Tower (Many Spikes / Warp Maze Room)" },
            { R156_GanonsTower_InvisibleFloorMazeRoom, "Ganon's Tower (Invisible Floor Maze Room)" },
            { R157_GanonsTower_CompassChest_InvisibleFloorRoom, "Ganon's Tower (Compass Chest / Invisible Floor Room)" },
            { R158_IcePalace_BigChestRoom, "Ice Palace (Big Chest Room)" },
            { R159_IcePalace0x9F, "Ice Palace (Room with ice floor, key, and 4 wall rats)" },
            { R160_MiseryMire_Pre_VitreousRoom, "Misery Mire (Pre-Vitreous Room)" },
            { R161_MiseryMire_FishRoom, "Misery Mire (Fish Room)" },
            { R162_MiseryMire_BridgeKeyChestRoom, "Misery Mire (Bridge Key Chest Room)" },
            { R163_MiseryMire0xA3, "Misery Mire (Empty 'L' connecting room)" },
            { R164_TurtleRock_Trinexx, "Turtle Rock (Trinexx[Boss])" },
            { R165_GanonsTower_WizzrobesRooms, "Ganon's Tower (Wizzrobes Rooms)" },
            { R166_GanonsTower_MoldormFallRoom, "Ganon's Tower (Moldorm Fall Room)" },
            { R167_TowerofHera_FairyRoom, "Tower of Hera (Fairy Room)" },
            { R168_EasternPalace_StalfosSpawnRoom, "Eastern Palace (Stalfos Spawn Room)" },
            { R169_EasternPalace_BigChestRoom, "Eastern Palace (Big Chest Room)" },
            { R170_EasternPalace_MapChestRoom, "Eastern Palace (Map Chest Room)" },
            { R171_ThievesTown_MovingSpikes_KeyPotRoom, "Thieves Town (Moving Spikes / Key Pot Room)" },
            { R172_ThievesTown_BlindTheThief, "Thieves Town (Blind The Thief[Boss])" },
            { R173_EmptyCloneRoom0xAD, "Empty Clone Room" },
            { R174_IcePalace0xAE, "Ice Palace (2 Blue Bari and Hidden Chest)" },
            { R175_IcePalace_IceBridgeRoom, "Ice Palace (Ice Bridge Room)" },
            { R176_AgahnimsTower_CircleofPots, "Agahnim's Tower (Circle of Pots)" },
            { R177_MiseryMire_HourglassRoom, "Misery Mire (Hourglass Room)" },
            { R178_MiseryMire_SlugRoom, "Misery Mire (Slug Room)" },
            { R179_MiseryMire_SpikeKeyChestRoom, "Misery Mire (Spike Key Chest Room)" },
            { R180_TurtleRock_Pre_TrinexxRoom, "Turtle Rock (Pre-Trinexx Room)" },
            { R181_TurtleRock_DarkMaze, "Turtle Rock (Dark Maze)" },
            { R182_TurtleRock_ChainChompsRoom, "Turtle Rock (Chain Chomps Room)" },
            { R183_TurtleRock_MapChest_KeyChest_RollerRoom, "Turtle Rock (Map Chest / Key Chest / Roller Room)" },
            { R184_EasternPalace_BigKeyRoom, "Eastern Palace (Big Key Room)" },
            { R185_EasternPalace_LobbyCannonballsRoom, "Eastern Palace (Lobby Cannonballs Room)" },
            { R186_EasternPalace_DarkAntifairy_KeyPotRoom, "Eastern Palace (Dark Antifairy / Key Pot Room)" },
            { R187_ThievesTown_Hellway, "Thieves Town (Hellway)" },
            { R188_ThievesTown_ConveyorToilet, "Thieves Town (Conveyor Toilet)" },
            { R189_EmptyCloneRoom0xBD, "Empty Clone Room" },
            { R190_IcePalace_BlockPuzzleRoom, "Ice Palace (Block Puzzle Room)" },
            { R191_IcePalaceCloneRoom_SwitchRoom, "Ice Palace Clone Room (Switch Room)" },
            { R192_AgahnimsTower_DarkBridgeRoom, "Agahnim's Tower (Dark Bridge Room)" },
            { R193_MiseryMire_CompassChest_TileRoom, "Misery Mire (Compass Chest / Tile Room)" },
            { R194_MiseryMire_BigHubRoom, "Misery Mire (Big Hub Room)" },
            { R195_MiseryMire_BigChestRoom, "Misery Mire (Big Chest Room)" },
            { R196_TurtleRock_FinalCrystalSwitchPuzzleRoom, "Turtle Rock (Final Crystal Switch Puzzle Room)" },
            { R197_TurtleRock_LaserBridge, "Turtle Rock (Laser Bridge)" },
            { R198_TurtleRock0xC6, "Turtle Rock (After Entrance Square Somaria Platform Room)" },
            { R199_TurtleRock_TorchPuzzle, "Turtle Rock (Torch Puzzle)" },
            { R200_EasternPalace_ArmosKnights, "Eastern Palace (Armos Knights[Boss])" },
            { R201_EasternPalace_EntranceRoom, "Eastern Palace (Entrance Room)" },
            { R202_UnknownRoom, "Unused room??" },
            { R203_ThievesTown_NorthWestEntranceRoom, "Thieves Town (North West Entrance Room)" },
            { R204_ThievesTown_NorthEastEntranceRoom, "Thieves Town (North East Entrance Room)" },
            { R205_EmptyCloneRoom0xCD, "Empty Clone Room" },
            { R206_IcePalace_HoletoKholdstareRoom, "Ice Palace (Hole to Kholdstare Room)" },
            { R207_EmptyCloneRoom0xCF, "Empty Clone Room" },
            { R208_AgahnimsTower_DarkMaze, "Agahnim's Tower (Dark Maze)" },
            { R209_MiseryMire_ConveyorSlug_BigKeyRoom, "Misery Mire (Conveyor Slug / Big Key Room)" },
            { R210_MiseryMire_Mire02_WizzrobesRoom, "Misery Mire (Mire02 / Wizzrobes Room)" },
            { R211_EmptyCloneRoom0xD3, "Empty Clone Room" },
            { R212_EmptyCloneRoom0xD4, "Empty Clone Room" },
            { R213_TurtleRock_LaserKeyRoom, "Turtle Rock (Laser Key Room)" },
            { R214_TurtleRock_EntranceRoom, "Turtle Rock (Entrance Room)" },
            { R215_EmptyCloneRoom0xD7, "Empty Clone Room" },
            { R216_EasternPalace_PreArmosKnightsRoom, "Eastern Palace ('Zeldagamer Room' / Pre-Armos Knights Room)" },
            { R217_EasternPalace_CanonballRoom, "Eastern Palace (Canonball Room)" },
            { R218_EasternPalace, "Eastern Palace (2 Bubble With Switch Under Pot)" },
            { R219_ThievesTown_Main_SouthWestEntranceRoom, "Thieves Town (Main (South West) Entrance Room)" },
            { R220_ThievesTown_SouthEastEntranceRoom, "Thieves Town (South East Entrance Room)" },
            { R221_EmptyCloneRoom0xDD, "Empty Clone Room" },
            { R222_IcePalace_Kholdstare, "Ice Palace (Kholdstare[Boss])" },
            { R223_Cave_BackwardsDeathMountainTopFloor, "'Top' of Backward Death-Mountain Cave" },
            { R224_AgahnimsTower_EntranceRoom, "Agahnim's Tower (Entrance Room)" },
            { R225_Cave_LostWoodsHP, "Cave (Lost Woods HP)" },
            { R226_Cave_LumberjacksTreeHP, "Cave (Lumberjack's Tree HP)" },
            { R227_Cave_HalfMagic, "Cave (1/2 Magic)" },
            { R228_Cave_LostOldManFinalCave, "Cave (Lost Old Man House Cave)" },
            { R229_Cave_LostOldManFinalCave2, "Cave (Lost Old Man House Cave Back)" },
            { R230_Cave0xE6, "Cave With a bunch of Keese" }, // TODO: figure out where this is
            { R231_Cave0xE7, "Cave With a bunch of Keese 2" }, // TODO: figure out where this is
            { R232_Cave0xE8, "Super Bunny Cave 'exit'" },
            { R233_EmptyCloneRoom0xE9, "Empty Clone Room" },
            { R234_Cave_SpectacleRockHP, "Cave (Inside Spectacle Rock HP)" },
            { R235_Cave0xEB, "Bumper Cave Entrance" },
            { R236_EmptyCloneRoom0xEC, "Empty Clone Room" },
            { R237_Cave0xED, "Cave (No clue)" }, // TODO: figure out where this is
            { R238_Cave_SpiralCave, "Cave (Spiral Cave)" },
            { R239_Cave_CrystalSwitch_5ChestsRoom, "Cave (Crystal Switch / 5 Chests Room)" },
            { R240_Cave_LostOldManStartingCave, "Cave (Lost Old Man Starting Cave Entrance)" },
            { R241_Cave_LostOldManStartingCave2, "Cave (Lost Old Man Starting Cave Exit)" },
            { R242_House, "House (Old Woman Next Door)" },
            { R243_House_OldWoman_SahasrahlasWifeMaybe, "House (Old Woman (Sahasrahla's Wife?))" },
            { R244_House_AngryBrothers, "House (Angry Brothers Exit to Maze Game)" },
            { R245_House_AngryBrothers2, "House (Angry Brothers Entrance)" },
            { R246_EmptyCloneRoom0xE6, "Empty Clone Room" },
            { R247_EmptyCloneRoom0xE7, "Empty Clone Room" },
            { R248_Cave0xF8, "Super Bunny Cave Entrance and Chests" },
            { R249_Cave0xF9, "Spectical Rock Cave (Exit after falling from top entrance)" },
            { R250_Cave0xFA, "Spectical Rock Cave (Entrance after jumping to get to HP)" },
            { R251_Cave0xFB, "Bumper Cave Entrance" },
            { R252_EmptyCloneRoom0xFC, "Empty Clone Room" },
            { R253_Cave0xFD, "Some Cave on Death-Mountain" }, // TODO: figure out where this is
            { R254_Cave0xFE, "Spiral Cave Exit after Falling" },
            { R255_Cave0xFF, "Upside-down Cave 'Middle' Entrance" },
            { R256_ShopInLostWoods0x100, "Shop in Lost Woods 0x100" },
            { R257_ScaredLadyHouses, "Scared Ladies' Houses" },
            { R258_SickKid, "Sick Kid" },
            { R259_Inn_BushHouse, "Inn / Bush House" },
            { R260_LinksHouse, "Link's House" },
            { R261_ShabadooHouse, "Sahasrahla's House" },
            { R262_ChestGame_BombHouse, "Chest Game / Outcast Village Bomb House" },
            { R263_Library_BombFarmRoom, "Library / Bomb Farm Room" },
            { R264_ChickenHouse, "Chicken House" },
            { R265_WitchHut, "Witch Hut" },
            { R266_Aginah, "Aginah's Cave" },
            { R267_SwampFloodwayRoom, "Swamp Floodway Room" },
            { R268_MimicCave, "Mimic Cave" },
            { R269_CaveOutsideMiseryMire, "Cave outside Misery Mire" },
            { R270_Cave0x10E, "Cave 0x10E (2 Unknown Caves)" }, // TODO: figure out where this is
            { R271_Shop0x10F, "Shop 0x10F" }, // TODO: figure out where this is
            { R272_Shop0x110, "Shop 0x110" }, // TODO: figure out where this is
            { R273_ArcherGame, "Archer Game" },
            { R274_CaveShop0x112, "Cave / Shop 0x112" }, // TODO: figure out where this is
            { R275_KingsTomb, "King's Tomb" },
            { R276_WishingWell_Cave0x114, "Wishing Well / Cave 0x114" },
            { R277_WishingWell_BigFairy, "Wishing Well / Big Fairy" },
            { R278_FatFairy, "Fat Fairy" },
            { R279_SpikeCave, "Spike Cave" },
            { R280_Shop0x118, "Shop 0x118" }, // TODO: figure out where this is
            { R281_BlindsHouse, "Blind's House" },
            { R282_Mutant, "Mutant Hut" }, // TODO: figure out where this is
            { R283_MirrorCaveGroveAndTomb, "Mirror Caves (South of Tree Boy / Above Kings Tomb)" },
            { R284_BombShop, "Bomb Shop" },
            { R285_BlindsBasement, "Blind's Basement" },
            { R286_HypeCave, "Hype Cave" },
            { R287_Shop0x11F, "Shop 0x11F" }, // TODO: figure out where this is
            { R288_IceRodCave, "Ice Rod Cave" },
            { R289_SmithHouse, "Smiths' House" },
            { R290_FortuneTellers, "Fortune Teller(s)" },
            { R291_MiniMoldormCave, "Mini-Moldorm Cave" },
            { R292_UnknownCave_BonkCave, "Unknown Cave / Bonk Cave" },
            { R293_Cave0x125, "Cave 0x125" }, // TODO: figure out where this is
            { R294_CheckerBoardCave, "Checker Board Cave" },
            { R295_HammerPegCave, "Hammer Peg Cave" },
        };


        public const int
            R0_Ganon = 0,
            R1_HyruleCastle_NorthCorridor = 1,
            R2_HyruleCastle_SwitchRoom = 2,
            R3_HoulihanRoom = 3,
            R4_TurtleRock_CrystalRollerRoom = 4,
            R5_EmptyCloneRoom0x05 = 5,
            R6_SwampPalace_Arrghus = 6,
            R7_TowerofHera_Moldorm = 7,
            R8_Cave_HealingFairy = 8,
            R9_PalaceofDarkness0x09 = 9,
            R10_PalaceofDarkness_StalfosTrapRoom = 10,
            R11_PalaceofDarkness_TurtleRoom = 11,
            R12_GanonsTower_EntranceRoom = 12,
            R13_GanonsTower_Agahnim2 = 13,
            R14_IcePalace_EntranceRoom = 14,
            R15_EmptyCloneRoom0x0F = 15,
            R16_GanonEvacuationRoute = 16,
            R17_HyruleCastle_BombableStockRoom = 17,
            R18_Sanctuary = 18,
            R19_TurtleRock_Hokku_BokkuKeyRoom2 = 19,
            R20_TurtleRock_BigKeyRoom = 20,
            R21_TurtleRock0x15 = 21,
            R22_SwampPalace_SwimmingTreadmill = 22,
            R23_TowerofHera_MoldormFallRoom = 23,
            R24_Cave0x18_BigFairyDropEntrance = 24,
            R25_PalaceofDarkness_DarkMaze = 25,
            R26_PalaceofDarkness_BigChestRoom = 26,
            R27_PalaceofDarkness_Mimics_MovingWallRoom = 27,
            R28_GanonsTower_IceArmos = 28,
            R29_GanonsTower_FinalHallway = 29,
            R30_IcePalace_BombFloor_BariRoom = 30,
            R31_IcePalace_Pengator_BigKeyRoom = 31,
            R32_AgahnimsTower_Agahnim = 32,
            R33_HyruleCastle_KeyRatRoom = 33,
            R34_HyruleCastle_SewerTextTriggerRoom = 34,
            R35_TurtleRock_WestExittoBalcony = 35,
            R36_TurtleRock_DoubleHokku_Bokku_BigchestRoom = 36,
            R37_EmptyCloneRoom0x25 = 37,
            R38_SwampPalace_StatueRoom = 38,
            R39_TowerofHera_BigChest = 39,
            R40_SwampPalace_EntranceRoom = 40,
            R41_SkullWoods_Mothula = 41,
            R42_PalaceofDarkness_BigHubRoom = 42,
            R43_PalaceofDarkness_MapChest_FairyRoom = 43,
            R44_Cave0x2C_HookshotCaveBackdoor = 44,
            R45_EmptyCloneRoom0x2D = 45,
            R46_IcePalace_CompassRoom = 46,
            R47_Cave_KakarikoWellHP = 47,
            R48_AgahnimsTower_MaidenSacrificeChamber = 48,
            R49_TowerofHera_HardhatBeetlesRoom = 49,
            R50_HyruleCastle_SewerKeyChestRoom = 50,
            R51_DesertPalace_Lanmolas = 51,
            R52_SwampPalace_PushBlockPuzzle_Pre_BigKeyRoom = 52,
            R53_SwampPalace_BigKey_BSRoom = 53,
            R54_SwampPalace_BigChestRoom = 54,
            R55_SwampPalace_MapChest_WaterFillRoom = 55,
            R56_SwampPalace_KeyPotRoom = 56,
            R57_SkullWoods_GibdoKey_MothulaHoleRoom = 57,
            R58_PalaceofDarkness_BombableFloorRoom = 58,
            R59_PalaceofDarkness_SpikeBlock_ConveyorRoom = 59,
            R60_Cave0x3C_HookshotCave = 60,
            R61_GanonsTower_TorchRoom2 = 61,
            R62_IcePalace_StalfosKnights_ConveyorHellway = 62,
            R63_IcePalace_MapChestRoom = 63,
            R64_AgahnimsTower_FinalBridgeRoom = 64,
            R65_HyruleCastle_FirstDarkRoom = 65,
            R66_HyruleCastle_6RopesRoom = 66,
            R67_DesertPalace_TorchPuzzle_MovingWallRoom = 67,
            R68_ThievesTown_BigChestRoom = 68,
            R69_ThievesTown_JailCellsRoom = 69,
            R70_SwampPalace_CompassChestRoom = 70,
            R71_EmptyCloneRoom0x47 = 71,
            R72_EmptyCloneRoom0x48 = 72,
            R73_SkullWoods_GibdoTorchPuzzleRoom = 73,
            R74_PalaceofDarkness_EntranceRoom = 74,
            R75_PalaceofDarkness_Warps_SouthMimicsRoom = 75,
            R76_GanonsTower_Mini_HelmasaurConveyorRoom = 76,
            R77_GanonsTower_MoldormRoom = 77,
            R78_IcePalace_Bomb_JumpRoom = 78,
            R79_IcePalaceCloneRoom_FairyRoom = 79,
            R80_HyruleCastle_WestCorridor = 80,
            R81_HyruleCastle_ThroneRoom = 81,
            R82_HyruleCastle_EastCorridor = 82,
            R83_DesertPalace_Popos2_BeamosHellwayRoom = 83,
            R84_SwampPalace_UpstairsPitsRoom = 84,
            R85_CastleSecretEntrance_UncleDeathRoom = 85,
            R86_SkullWoods_KeyPot_TrapRoom = 86,
            R87_SkullWoods_BigKeyRoom = 87,
            R88_SkullWoods_BigChestRoom = 88,
            R89_SkullWoods_FinalSectionEntranceRoom = 89,
            R90_PalaceofDarkness_HelmasaurKing = 90,
            R91_GanonsTower_SpikePitRoom = 91,
            R92_GanonsTower_Ganon_BallZ = 92,
            R93_GanonsTower_Gauntlet1_2_3 = 93,
            R94_IcePalace_LonelyFirebar = 94,
            R95_IcePalace_HiddenChest_SpikeFloorRoom = 95,
            R96_HyruleCastle_WestEntranceRoom = 96,
            R97_HyruleCastle_MainEntranceRoom = 97,
            R98_HyruleCastle_EastEntranceRoom = 98,
            R99_DesertPalace_FinalSectionEntranceRoom = 99,
            R100_ThievesTown_WestAtticRoom = 100,
            R101_ThievesTown_EastAtticRoom = 101,
            R102_SwampPalace_HiddenChest_HiddenDoorRoom = 102,
            R103_SkullWoods_CompassChestRoom = 103,
            R104_SkullWoods_KeyChest_TrapRoom = 104,
            R105_EmptyCloneRoom0x69 = 105,
            R106_PalaceofDarkness_RupeeRoom = 106,
            R107_GanonsTower_MimicsRooms = 107,
            R108_GanonsTower_LanmolasRoom = 108,
            R109_GanonsTower_Gauntlet4_5 = 109,
            R110_IcePalace_PengatorsRoom = 110,
            R111_EmptyCloneRoom0x6F = 111,
            R112_HyruleCastle_SmallCorridortoJailCells = 112,
            R113_HyruleCastle_BoomerangChestRoom = 113,
            R114_HyruleCastle_MapChestRoom = 114,
            R115_DesertPalace_BigChestRoom = 115,
            R116_DesertPalace_MapChestRoom = 116,
            R117_DesertPalace_BigKeyChestRoom = 117,
            R118_SwampPalace_WaterDrainRoom = 118,
            R119_TowerofHera_EntranceRoom = 119,
            R120_EmptyCloneRoom0x78 = 120,
            R121_EmptyCloneRoom0x79 = 121,
            R122_EmptyCloneRoom0x7A = 122,
            R123_GanonsTower = 123,
            R124_GanonsTower_EastSideCollapsingBridge_ExplodingWallRoom = 124,
            R125_GanonsTower_Winder_WarpMazeRoom = 125,
            R126_IcePalace_HiddenChest_BombableFloorRoom = 126,
            R127_IcePalace_BigSpikeTrapsRoom = 127,
            R128_HyruleCastle_JailCellRoom = 128,
            R129_HyruleCastle_NextToChasmRoom = 129,
            R130_HyruleCastle_BasementChasmRoom = 130,
            R131_DesertPalace_WestEntranceRoom = 131,
            R132_DesertPalace_MainEntranceRoom = 132,
            R133_DesertPalace_EastEntranceRoom = 133,
            R134_EmptyCloneRoom0x86 = 134,
            R135_TowerofHera_TileRoom = 135,
            R136_EmptyCloneRoom0x88 = 136,
            R137_EasternPalace_FairyRoom = 137,
            R138_EmptyCloneRoom0x8A = 138,
            R139_GanonsTower_BlockPuzzle_SpikeSkip_MapChestRoom = 139,
            R140_GanonsTower_EastandWestDownstairs_BigChestRoom = 140,
            R141_GanonsTower_Tile_TorchPuzzleRoom = 141,
            R142_IcePalace0x8E = 142,
            R143_EmptyCloneRoom0x8F = 143,
            R144_MiseryMire_Vitreous = 144,
            R145_MiseryMire_FinalSwitchRoom = 145,
            R146_MiseryMire_DarkBombWall_SwitchesRoom = 146,
            R147_MiseryMire_DarkCaneFloorSwitchPuzzleRoom = 147,
            R148_EmptyCloneRoom0x94 = 148,
            R149_GanonsTower_FinalCollapsingBridgeRoom = 149,
            R150_GanonsTower_Torches1Room = 150,
            R151_MiseryMire_TorchPuzzle_MovingWallRoom = 151,
            R152_MiseryMire_EntranceRoom = 152,
            R153_EasternPalace_EyegoreKeyRoom = 153,
            R154_EmptyCloneRoom0x9A = 154,
            R155_GanonsTower_ManySpikes_WarpMazeRoom = 155,
            R156_GanonsTower_InvisibleFloorMazeRoom = 156,
            R157_GanonsTower_CompassChest_InvisibleFloorRoom = 157,
            R158_IcePalace_BigChestRoom = 158,
            R159_IcePalace0x9F = 159,
            R160_MiseryMire_Pre_VitreousRoom = 160,
            R161_MiseryMire_FishRoom = 161,
            R162_MiseryMire_BridgeKeyChestRoom = 162,
            R163_MiseryMire0xA3 = 163,
            R164_TurtleRock_Trinexx = 164,
            R165_GanonsTower_WizzrobesRooms = 165,
            R166_GanonsTower_MoldormFallRoom = 166,
            R167_TowerofHera_FairyRoom = 167,
            R168_EasternPalace_StalfosSpawnRoom = 168,
            R169_EasternPalace_BigChestRoom = 169,
            R170_EasternPalace_MapChestRoom = 170,
            R171_ThievesTown_MovingSpikes_KeyPotRoom = 171,
            R172_ThievesTown_BlindTheThief = 172,
            R173_EmptyCloneRoom0xAD = 173,
            R174_IcePalace0xAE = 174,
            R175_IcePalace_IceBridgeRoom = 175,
            R176_AgahnimsTower_CircleofPots = 176,
            R177_MiseryMire_HourglassRoom = 177,
            R178_MiseryMire_SlugRoom = 178,
            R179_MiseryMire_SpikeKeyChestRoom = 179,
            R180_TurtleRock_Pre_TrinexxRoom = 180,
            R181_TurtleRock_DarkMaze = 181,
            R182_TurtleRock_ChainChompsRoom = 182,
            R183_TurtleRock_MapChest_KeyChest_RollerRoom = 183,
            R184_EasternPalace_BigKeyRoom = 184,
            R185_EasternPalace_LobbyCannonballsRoom = 185,
            R186_EasternPalace_DarkAntifairy_KeyPotRoom = 186,
            R187_ThievesTown_Hellway = 187,
            R188_ThievesTown_ConveyorToilet = 188,
            R189_EmptyCloneRoom0xBD = 189,
            R190_IcePalace_BlockPuzzleRoom = 190,
            R191_IcePalaceCloneRoom_SwitchRoom = 191,
            R192_AgahnimsTower_DarkBridgeRoom = 192,
            R193_MiseryMire_CompassChest_TileRoom = 193,
            R194_MiseryMire_BigHubRoom = 194,
            R195_MiseryMire_BigChestRoom = 195,
            R196_TurtleRock_FinalCrystalSwitchPuzzleRoom = 196,
            R197_TurtleRock_LaserBridge = 197,
            R198_TurtleRock0xC6 = 198,
            R199_TurtleRock_TorchPuzzle = 199,
            R200_EasternPalace_ArmosKnights = 200,
            R201_EasternPalace_EntranceRoom = 201,
            R202_UnknownRoom = 202,
            R203_ThievesTown_NorthWestEntranceRoom = 203,
            R204_ThievesTown_NorthEastEntranceRoom = 204,
            R205_EmptyCloneRoom0xCD = 205,
            R206_IcePalace_HoletoKholdstareRoom = 206,
            R207_EmptyCloneRoom0xCF = 207,
            R208_AgahnimsTower_DarkMaze = 208,
            R209_MiseryMire_ConveyorSlug_BigKeyRoom = 209,
            R210_MiseryMire_Mire02_WizzrobesRoom = 210,
            R211_EmptyCloneRoom0xD3 = 211,
            R212_EmptyCloneRoom0xD4 = 212,
            R213_TurtleRock_LaserKeyRoom = 213,
            R214_TurtleRock_EntranceRoom = 214,
            R215_EmptyCloneRoom0xD7 = 215,
            R216_EasternPalace_PreArmosKnightsRoom = 216,
            R217_EasternPalace_CanonballRoom = 217,
            R218_EasternPalace = 218,
            R219_ThievesTown_Main_SouthWestEntranceRoom = 219,
            R220_ThievesTown_SouthEastEntranceRoom = 220,
            R221_EmptyCloneRoom0xDD = 221,
            R222_IcePalace_Kholdstare = 222,
            R223_Cave_BackwardsDeathMountainTopFloor = 223,
            R224_AgahnimsTower_EntranceRoom = 224,
            R225_Cave_LostWoodsHP = 225,
            R226_Cave_LumberjacksTreeHP = 226,
            R227_Cave_HalfMagic = 227,
            R228_Cave_LostOldManFinalCave = 228,
            R229_Cave_LostOldManFinalCave2 = 229,
            R230_Cave0xE6 = 230,
            R231_Cave0xE7 = 231,
            R232_Cave0xE8 = 232,
            R233_EmptyCloneRoom0xE9 = 233,
            R234_Cave_SpectacleRockHP = 234,
            R235_Cave0xEB = 235,
            R236_EmptyCloneRoom0xEC = 236,
            R237_Cave0xED = 237,
            R238_Cave_SpiralCave = 238,
            R239_Cave_CrystalSwitch_5ChestsRoom = 239,
            R240_Cave_LostOldManStartingCave = 240,
            R241_Cave_LostOldManStartingCave2 = 241,
            R242_House = 242,
            R243_House_OldWoman_SahasrahlasWifeMaybe = 243,
            R244_House_AngryBrothers = 244,
            R245_House_AngryBrothers2 = 245,
            R246_EmptyCloneRoom0xE6 = 246,
            R247_EmptyCloneRoom0xE7 = 247,
            R248_Cave0xF8 = 248,
            R249_Cave0xF9 = 249,
            R250_Cave0xFA = 250,
            R251_Cave0xFB = 251,
            R252_EmptyCloneRoom0xFC = 252,
            R253_Cave0xFD = 253,
            R254_Cave0xFE = 254,
            R255_Cave0xFF = 255,
            R256_ShopInLostWoods0x100 = 256,
            R257_ScaredLadyHouses = 257,
            R258_SickKid = 258,
            R259_Inn_BushHouse = 259,
            R260_LinksHouse = 260,
            R261_ShabadooHouse = 261,
            R262_ChestGame_BombHouse = 262,
            R263_Library_BombFarmRoom = 263,
            R264_ChickenHouse = 264,
            R265_WitchHut = 265,
            R266_Aginah = 266,
            R267_SwampFloodwayRoom = 267,
            R268_MimicCave = 268,
            R269_CaveOutsideMiseryMire = 269,
            R270_Cave0x10E = 270,
            R271_Shop0x10F = 271,
            R272_Shop0x110 = 272,
            R273_ArcherGame = 273,
            R274_CaveShop0x112 = 274,
            R275_KingsTomb = 275,
            R276_WishingWell_Cave0x114 = 276,
            R277_WishingWell_BigFairy = 277,
            R278_FatFairy = 278,
            R279_SpikeCave = 279,
            R280_Shop0x118 = 280,
            R281_BlindsHouse = 281,
            R282_Mutant = 282,
            R283_MirrorCaveGroveAndTomb = 283,
            R284_BombShop = 284,
            R285_BlindsBasement = 285,
            R286_HypeCave = 286,
            R287_Shop0x11F = 287,
            R288_IceRodCave = 288,
            R289_SmithHouse = 289,
            R290_FortuneTellers = 290,
            R291_MiniMoldormCave = 291,
            R292_UnknownCave_BonkCave = 292,
            R293_Cave0x125 = 293,
            R294_CheckerBoardCave = 294,
            R295_HammerPegCave = 295;

        //All the rooms that need every sprite dead for doors to open
        public static readonly int[] NeedKillable_doors =
        {
            R184_EasternPalace_BigKeyRoom, // for the anti-fairy circle

            R11_PalaceofDarkness_TurtleRoom,
            R27_PalaceofDarkness_Mimics_MovingWallRoom,
            R75_PalaceofDarkness_Warps_SouthMimicsRoom,

            R36_TurtleRock_DoubleHokku_Bokku_BigchestRoom,
            R182_TurtleRock_ChainChompsRoom,

            R40_SwampPalace_EntranceRoom,

            R46_IcePalace_CompassRoom,
            R62_IcePalace_StalfosKnights_ConveyorHellway,
            R110_IcePalace_PengatorsRoom,

            R49_TowerofHera_HardhatBeetlesRoom,
            R135_TowerofHera_TileRoom,

            R68_ThievesTown_BigChestRoom,
            R69_ThievesTown_JailCellsRoom,

            R83_DesertPalace_Popos2_BeamosHellwayRoom,
            R117_DesertPalace_BigKeyChestRoom,
            R133_DesertPalace_EastEntranceRoom,

            R93_GanonsTower_Gauntlet1_2_3,
            R107_GanonsTower_MimicsRooms,
            R109_GanonsTower_Gauntlet4_5,
            R123_GanonsTower,
            R125_GanonsTower_Winder_WarpMazeRoom,
            R141_GanonsTower_Tile_TorchPuzzleRoom,
            R165_GanonsTower_WizzrobesRooms,

            R113_HyruleCastle_BoomerangChestRoom,

            R168_EasternPalace_StalfosSpawnRoom,
            R216_EasternPalace_PreArmosKnightsRoom,

            R176_AgahnimsTower_CircleofPots,
            R224_AgahnimsTower_EntranceRoom,

            R178_MiseryMire_SlugRoom,
            R210_MiseryMire_Mire02_WizzrobesRoom,

            R239_Cave_CrystalSwitch_5ChestsRoom,

            R268_MimicCave,

            R291_MiniMoldormCave
        };
        //room 113 is not in needkillable is it in key_sprite?

        //All the rooms that require special handling
        public static readonly int[] IcemanRoom =
        {
            R14_IcePalace_EntranceRoom,
            R126_IcePalace_HiddenChest_BombableFloorRoom,
            R142_IcePalace0x8E,
            R158_IcePalace_BigChestRoom,
            R190_IcePalace_BlockPuzzleRoom
        }; //these room need to be locked on the gfx ID : 28

        public static readonly int[] WaterRoom =
        {
            R22_SwampPalace_SwimmingTreadmill,
            R40_SwampPalace_EntranceRoom,
            R52_SwampPalace_PushBlockPuzzle_Pre_BigKeyRoom,
            R54_SwampPalace_BigChestRoom,
            R56_SwampPalace_KeyPotRoom,
            R70_SwampPalace_CompassChestRoom,
            R102_SwampPalace_HiddenChest_HiddenDoorRoom
        }; //these room need to be locked on the gfx ID : 17 //118 removed

        public static readonly int[] ShadowRoom =
        {
            R62_IcePalace_StalfosKnights_ConveyorHellway,
            R159_IcePalace0x9F
        };//28,27,30

        public static readonly int[] WallMasterRoom =
        {
            R57_SkullWoods_GibdoKey_MothulaHoleRoom,
            R73_SkullWoods_GibdoTorchPuzzleRoom,
            R86_SkullWoods_KeyPot_TrapRoom,
            R104_SkullWoods_KeyChest_TrapRoom,
            R141_GanonsTower_Tile_TorchPuzzleRoom
        };//force 82 on 3

        public static readonly int[] bumperandcrystalRoom =
        {
            R23_TowerofHera_MoldormFallRoom,
            R4_TurtleRock_CrystalRollerRoom,
            R11_PalaceofDarkness_TurtleRoom,
            R19_TurtleRock_Hokku_BokkuKeyRoom2,
            R27_PalaceofDarkness_Mimics_MovingWallRoom,
            R30_IcePalace_BombFloor_BariRoom,
            R42_PalaceofDarkness_BigHubRoom,
            R43_PalaceofDarkness_MapChest_FairyRoom,
            R49_TowerofHera_HardhatBeetlesRoom,
            R68_ThievesTown_BigChestRoom,
            R76_GanonsTower_Mini_HelmasaurConveyorRoom,
            R88_SkullWoods_BigChestRoom,
            R89_SkullWoods_FinalSectionEntranceRoom,
            R91_GanonsTower_SpikePitRoom,
            R103_SkullWoods_CompassChestRoom,
            R104_SkullWoods_KeyChest_TrapRoom,
            R107_GanonsTower_MimicsRooms,
            R119_TowerofHera_EntranceRoom,
            R135_TowerofHera_TileRoom,
            R139_GanonsTower_BlockPuzzle_SpikeSkip_MapChestRoom,
            R145_MiseryMire_FinalSwitchRoom,
            R150_GanonsTower_Torches1Room,
            R146_MiseryMire_DarkBombWall_SwitchesRoom,
            R155_GanonsTower_ManySpikes_WarpMazeRoom,
            R157_GanonsTower_CompassChest_InvisibleFloorRoom,
            R161_MiseryMire_FishRoom,
            R171_ThievesTown_MovingSpikes_KeyPotRoom,
            R182_TurtleRock_ChainChompsRoom,
            R191_IcePalaceCloneRoom_SwitchRoom,
            R193_MiseryMire_CompassChest_TileRoom,
            R196_TurtleRock_FinalCrystalSwitchPuzzleRoom,
            R235_Cave0xEB,
            R64_AgahnimsTower_FinalBridgeRoom,
            R74_PalaceofDarkness_EntranceRoom,
            R165_GanonsTower_WizzrobesRooms,
            R195_MiseryMire_BigChestRoom,
            R197_TurtleRock_LaserBridge,
            R213_TurtleRock_LaserKeyRoom,
            R214_TurtleRock_EntranceRoom,
            R239_Cave_CrystalSwitch_5ChestsRoom,
            R61_GanonsTower_TorchRoom2,
            R126_IcePalace_HiddenChest_BombableFloorRoom
        };//also laser shooting eyes //can be 82 or 83 on 3
        //126 IR,

        public static readonly int[] SwitchesRoom =
        {
            R2_HyruleCastle_SwitchRoom,
            R88_SkullWoods_BigChestRoom,
            R100_ThievesTown_WestAtticRoom,
            R267_SwampFloodwayRoom
        };// WM, ?? 73:no switch in that room

        public static readonly int[] TonguesRoom =
        {
            R4_TurtleRock_CrystalRollerRoom,
            R35_TurtleRock_WestExittoBalcony,
            R53_SwampPalace_BigKey_BSRoom,
            R55_SwampPalace_MapChest_WaterFillRoom,
            R63_IcePalace_MapChestRoom,
            R118_SwampPalace_WaterDrainRoom,
            R206_IcePalace_HoletoKholdstareRoom
        };

        //byte[] PushSwitchesRoom = { 53, 55, 118 }; //83 same as tongue

        public static readonly int[] noStatueRoom =
        {
            R22_SwampPalace_SwimmingTreadmill,
            R38_SwampPalace_StatueRoom,
            R40_SwampPalace_EntranceRoom,
            R43_PalaceofDarkness_MapChest_FairyRoom,
            R52_SwampPalace_PushBlockPuzzle_Pre_BigKeyRoom,
            R54_SwampPalace_BigChestRoom,
            R70_SwampPalace_CompassChestRoom,
            R87_SkullWoods_BigKeyRoom,
            R118_SwampPalace_WaterDrainRoom,
            R177_MiseryMire_HourglassRoom,
            R194_MiseryMire_BigHubRoom,
            R208_AgahnimsTower_DarkMaze
        }; //do not generate statue in these rooms
        //ROOM 127 do not spawn  anti-faerie

        public static readonly int[] canonRoom =
        {
            R92_GanonsTower_Ganon_BallZ,
            R117_DesertPalace_BigKeyChestRoom
        }; //47 on 0

        public static readonly int[] canonRoom2 =
        {
            R185_EasternPalace_LobbyCannonballsRoom,
            R217_EasternPalace_CanonballRoom,
            R268_MimicCave
        };//46 on 2

        public static readonly int[] RandomizeRooms =
        {
            2,4,9,10,11,14,17,19,21,22,23,25,26,27,30,31,33,34,36,38,39,40,42,43,46,49,50,52,53,54,55,56,57,58,59,
            60,61,62,63,64,65,66,67,68,69,70,73,74,75,76,78,80,81,82,83,84,85,86,87,88,89,91,92,93,94,95,96,97,98,99,
            100,101,102,103,104,106,107,109,110,113,114,115,116,117,118,119,123,124,125,126,127,128,129,130,131,132,133,
            135,139,140,141,142,145,146,147,149,151,152,153,155,156,157,158,159,160,161,165,166,167,168,169,170,171,174,
            175,176,177,178,179,182,183,184,186,187,188,190,192,193,194,195,196,197,201,203,204,206,208,209,210,213,214,
            216,217,218,219,220,223,224,228,232,238,239,240,249,251,235,254,263,264,268,269,291,267,185,286,181,150,
            R200_EasternPalace_ArmosKnights,
            R51_DesertPalace_Lanmolas,
            R108_GanonsTower_LanmolasRoom,
            R7_TowerofHera_Moldorm,
            R77_GanonsTower_MoldormRoom,
            R90_PalaceofDarkness_HelmasaurKing,
            R6_SwampPalace_Arrghus,
            R41_SkullWoods_Mothula,
            R172_ThievesTown_BlindTheThief,
            R222_IcePalace_Kholdstare,
            R144_MiseryMire_Vitreous,
            R164_TurtleRock_Trinexx
        };

        public static readonly int[] BossRooms =
        {
            R200_EasternPalace_ArmosKnights,
            R51_DesertPalace_Lanmolas,
            R108_GanonsTower_LanmolasRoom,
            R7_TowerofHera_Moldorm,
            R77_GanonsTower_MoldormRoom,
            R90_PalaceofDarkness_HelmasaurKing,
            R6_SwampPalace_Arrghus,
            R41_SkullWoods_Mothula,
            R172_ThievesTown_BlindTheThief,
            R222_IcePalace_Kholdstare,
            R144_MiseryMire_Vitreous,
            R164_TurtleRock_Trinexx,
            R32_AgahnimsTower_Agahnim,
            R13_GanonsTower_Agahnim2,
            R0_Ganon
        };
    }
}
