sprite_bush_spawn_table:
{
    ; SPRITE DATA TABLE GENERATED BY ENEMIZER
    .overworld
    ; Skip 0x128(overworld [way overkill]) + 0x128 (dungeons)
    skip #$128
    .dungeons
    skip #$128

    ;Old sprite table - Could be changed as well (for the item id 04)
    .random_sprites ; if item == 04
    db  #$00, #$D8, #$E3, #$D8
}
