using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EnemizerLibrary
{
    public class EntranceConstants
    {
        public static string GetEntranceSourceName(int entrance)
        {
            string ret = "";
            if (EntranceSource.TryGetValue(entrance, out ret))
            {
                return ret;
            }
            return null;
        }
        public readonly static Dictionary<int, string> EntranceSource = new Dictionary<int, string>()
        {
            { 0x00, "002C : Link's house (Door)" },
            { 0x01, "0013 : Sanctuary (Main Entrance)" },
            { 0x02, "001B : Hyrule Castle (Left Entrance)" },
            { 0x03, "001B : Hyrule Castle (Main Entrance)" },
            { 0x04, "001B : Hyrule Castle (Right Entrance)" },
            { 0x05, "000A : Old man cave (Lower Entrance)" },
            { 0x06, "0003 : Old man cave (DM Entrance)" },
            { 0x07, "001E : Eastern Palace (Main Entrance)" },
            { 0x08, "0030 : Desert Palace (Main Entrance)" },
            { 0x09, "0030 : Desert Palace (Right Entrance)" },
            { 0x0A, "0030 : Desert Palace (Left Entrance)" },
            { 0x0B, "0030 : Desert Palace (Boss Entrance)" },
            { 0x0C, "0018 : Kakariko double house (Left Entrance)" },
            { 0x0D, "0018 : Kakariko double house (Right Entrance)" },
            { 0x0E, "0028 : Angry brother house (Left Entrance)" },
            { 0x0F, "0029 : Angry brother house (Right Entrance)" },
            { 0x10, "0022 : Smith Cave (Main Entrance)" },
            { 0x11, "0002 : Agahnim Tree Cave (Cave Entrance)" },
            { 0x12, "0045 : (DW)DMR Bottom Left (Cave Entrance)" },
            { 0x13, "0045 : (DW)DMR Top cave" },
            { 0x14, "0045 : (DW)Turtle Rock Laser eyes (Bomb Cave Entrance)" },
            { 0x15, "004A : (DW)Bumper Cave Bottom Entrance (Cave Entrance)" },
            { 0x16, "004A : (DW)Bumper Cave Top Entrance (Cave Entrance)" },
            { 0x17, "0045 : (DW)Turtle Rock Laser Skip (Bomb Cave Entrance)" },
            { 0x18, "0045 : (DW)Turtle Rock Big Chest (Cave Entrance)" },
            { 0x19, "0005 : (LW)DMR Black rocks cave (Cave Entrance)" },
            { 0x1A, "0005 : (LW)DMR Middle cave via drop (Cave Entrance)" },
            { 0x1B, "0005 : (LW)DMR Spiral Cave (Cave Exit)" },
            { 0x1C, "0005 : (LW)DMR Spiral Cave via drop (Cave Entrance)" },
            { 0x1D, "0005 : (LW)DMR Bottom Right 2 Caves (Cave Entrance)" },
            { 0x1E, "0005 : (LW)DMR Bottom Right (Cave Entrance)" },
            { 0x1F, "0005 : (LW)DMR Top Right (Cave Entrance)" },
            { 0x20, "0003 : (LW)DML Top Left via drop (kikiskip) (Cave Entrance)" },
            { 0x21, "0003 : (LW)DML Top Middle via drop (Cave Entrance)" },
            { 0x22, "0003 : (LW)DML Top Middle Spectacle rock (Cave Entrance)" },
            { 0x23, "001B : (LW)Agahnim Tower" },
            { 0x24, "007B : (DW)Swamp Palace" },
            { 0x25, "005E : (DW)Palace Of Darkness" },
            { 0x26, "0070 : (DW)Misery Mire" },
            { 0x27, "0040 : (DW)Skull Woods (Entrance with Bumper / Key Pot)" },
            { 0x28, "0040 : (DW)Skull Woods (Statue Push Entrance)" },
            { 0x29, "0040 : (DW)Skull Woods (Big Chest Entrance)" },
            { 0x2A, "0040 : (DW)Skull Woods (Boss part Entrance)" },
            { 0x2B, "0000 : (LW)Woods Heart Piece (Tree Entrance)" },
            { 0x2C, "0075 : (DW)Ice Palace Entrance" },
            { 0x2D, "000A : (LW)6 holes cave exit of DM" },
            { 0x2E, "0003 : (LW)DML Long ladder cave" },
            { 0x2F, "0003 : (LW)DML Old Man (healing) cave" },
            { 0x30, "0003 : (LW)DML Bottom Cave (old man exit)" },
            { 0x31, "001B : (LW)Secret bush entrance (Door)" },
            { 0x32, "0003 : (LW)Tower of Hera" },
            { 0x33, "0058 : (DW)Thieves Town" },
            { 0x34, "0047 : (DW)Turtle Rock (Main Entrance)" },
            { 0x35, "005B : (DW)Pyramid Entrance between 2 statue" },
            { 0x36, "0043 : (DW)Ganon's Tower" },
            { 0x37, "0015 : (LW)Right side of Cemetary (cave entrance)" },
            { 0x38, "0018 : (LW)Kakariko Well (Door)" },
            { 0x39, "0045 : (DW)DMR Top Right (under rock)" },
            { 0x3A, "0045 : (DW)DMR Door leading to floating island" },
            { 0x3B, "0000 : (DW)3Chest Minigame in the woods" },
            { 0x3C, "0074 : (DW)Npc cave top right of swamp" },
            { 0x3D, "0018 : (LW)Kakariko Right House" },
            { 0x3E, "0018 : (LW)Kakariko Left House" },
            { 0x3F, "0018 : (LW)Kakariko Sickboy house" },
            { 0x40, "0043 : (LW)DML Spike cave" },
            { 0x41, "0018 : (LW)Tavern Main Entrance" },
            { 0x42, "0018 : (LW)Tavern Back Entrance" },
            { 0x43, "0018 : (LW)Kakariko Bushes House" },
            { 0x44, "001E : (LW)Sarahsrala's Hut" },
            { 0x45, "0018 : (LW)Kakariko SHOP" },
            { 0x46, "0058 : (DW)Chest Minigame" },
            { 0x47, "0058 : (DW)300 rupees,Redboom hut" },
            { 0x48, "0029 : (LW)Library" },
            { 0x49, "0018 : (LW)Secret bombhouse Kakariko" },
            { 0x4A, "0018 : (LW)Chicken House" },
            { 0x4B, "0016 : (LW)Witch Potion Shop" },
            { 0x4C, "0030 : (LW)Desert Aginah Cave" },
            { 0x4D, "003B : (LW)DAM Entrance" },
            { 0x4E, "0005 : (LW)DMR Mimic cave" },
            { 0x4F, "0005 : (LW)DMR Fairyhookshot cave" },
            { 0x50, "0032 : (LW)Mirror cave under flute location" },
            { 0x51, "0014 : (LW)Cemetary Mirror Cave" },
            { 0x52, "006C : (DW)Link's House Bomb shop" },
            { 0x53, "0058 : (DW)C-Shaped House Kakariko" },
            { 0x54, "002F : (LW)Fairy Cave Flute #5" },
            { 0x55, "0070 : (DW)Misery Mire right entrance" },
            { 0x56, "0042 : (DW)Lumberjack shop" },
            { 0x57, "0035 : (LW)Hylia Lake shop" },
            { 0x58, "0069 : (DW)Archery Game" },
            { 0x59, "0053 : (DW)Sanctuary Cave" },
            { 0x5A, "0014 : (LW)Cape Grave Entrance" },
            { 0x5B, "000F : (LW)Waterfall Pond" },
            { 0x5C, "0035 : (LW)Arrow/Bombs Pond" },
            { 0x5D, "002E : (LW)FairyCave South of Eastern palace" },
            { 0x5E, "0070 : (DW)Left Mire Entrance (2 chest)" },
            { 0x5F, "0058 : (DW)Kakariko Shop" },
            { 0x60, "0018 : (LW)Thieves Hut" },
            { 0x61, "0070 : (DW)Desert Cave" },
            { 0x62, "005B : (DW)Pyramid Pond" },
            { 0x63, "0022 : (LW)Smith House" },
            { 0x64, "0011 : (LW)Fortune Teller North of Kakariko" },
            { 0x65, "0051 : (DW)Fortune Teller North of Kakariko" },
            { 0x66, "0029 : (LW)3 Chest minigame" },
            { 0x67, "005E : (DW)MiniTree? House (Palace of darkness Area)" },
            { 0x68, "006F : (DW)Flute #5 Cave" },
            { 0x69, "0077 : (DW)Ice Rod NPC Cave" },
            { 0x6A, "0037 : (LW)Ice rod cave (Right cave)" },
            { 0x6B, "0034 : (LW)FairyCave South of link's house" },
            { 0x6C, "006E : (DW)FairyCave Sount of Palace of Darkness" },
            { 0x6D, "0045 : (DW)CaveSHOP on DM" },
            { 0x6E, "0056 : (DW)Witch Shop (DW)" },
            { 0x6F, "0043 : (DW)DML FairyCave" },
            { 0x70, "0030 : (LW)Desert Aginah Cave" },
            { 0x71, "003A : (LW)FairyCave Before desert" },
            { 0x72, "0035 : (LW)Fortune Teller Hylia Lake" },
            { 0x73, "0075 : (DW)SHOP Hylia Lake" },
            { 0x74, "005A : (DW)Lonely Shop West of pyramid" },
            { 0x75, "0002 : (LW)Lumberjack SHOP" },
            { 0x76, "002B : (LW)link's fairy cave" },
            { 0x77, "006B : (DW)link's fairy cave" },
            { 0x78, "003A : (LW)Thief Cave before Desert" },
            { 0x79, "0013 : (LW)Sanctuary under rock cave" },
            { 0x7A, "0037 : (LW)Thief Cave near ice rod" },
            { 0x7B, "0077 : (DW)Ice rod cave under the rock" },
            { 0x7C, "0035 : (LW)Minimoldorm cave hylia lake" },
            { 0x7D, "0030 : (LW)Desert mirror block maze" },
            { 0x7E, "0062 : (DW)Smith Pegs Cave" },
            { 0x7F, "0037 : (LW)Ice Rod Cave (Left Entrance)" },
            { 0x80, "0077 : (DW)FairyCave (Ice rod cave)" },
        };

        public static string GetEntranceNameFromAddress(int address)
        {
            string ret = "";
            if(EntranceAddressNames.TryGetValue(address, out ret))
            {
                return ret;
            }
            return null;
        }

        public readonly static Dictionary<int, string> EntranceAddressNames = new Dictionary<int, string>()
        {
            {0xDB84C,"Skull Woods First Section Hole (North)"},
            {0xDB84D,"Skull Woods First Section Hole (East)"},
            // 0xDB84E = dup?
            {0xDB84F,"Skull Woods First Section Hole (West)"},
            // 0xDB850 = dup?
            {0xDB851,"Skull Woods Second Section Hole"},
            // 0xDB852 = dup?
            {0xDB853,"Thieves Forest Hideout Drop"},
            {0xDB854,"Pyramid Hole"},
            // 0xDB855 = dup?
            // 0xDB856 = dup?
            {0xDB857,"North Fairy Cave Drop"},
            {0xDB858,"Hyrule Castle Secret Entrance Drop"},
            {0xDB859,"Bat Cave Drop"},
            // 0xDB85A = dup?
            {0xDB85B,"Lumberjack Tree Tree"},
            {0xDB85C,"Kakariko Well Drop"},
            // 0xDB85D = dup?
            {0xDB85E,"Sanctuary Grave"},
            {0xDBB73,"Link's House"},
            {0xDBB74,"Sanctuary"},
            {0xDBB75,"Hyrule Castle Entrance (West)"},
            {0xDBB76,"Hyrule Castle Entrance (South)"},
            {0xDBB77,"Hyrule Castle Entrance (East)"},
            {0xDBB78,"Old Man Cave (West)"},
            {0xDBB79,"Old Man Cave (East)"},
            {0xDBB7A,"Eastern Palace"},
            {0xDBB7B,"Desert Palace Entrance (South)"},
            {0xDBB7C,"Desert Palace Entrance (East)"},
            {0xDBB7D,"Desert Palace Entrance (West)"},
            {0xDBB7E,"Desert Palace Entrance (North)"},
            {0xDBB7F,"Elder House (West)"},
            {0xDBB80,"Elder House (East)"},
            {0xDBB81,"Two Brothers House (West)"},
            {0xDBB82,"Two Brothers House (East)"},
            {0xDBB83,"Bat Cave Cave"},
            {0xDBB84,"Lumberjack Tree Cave"},
            {0xDBB85,"Dark Death Mountain Ascend (Bottom)"},
            {0xDBB86,"Dark Death Mountain Ascend (Top)"},
            {0xDBB87,"Dark Death Mountain Ledge (West)"},
            {0xDBB88,"Bumper Cave (Bottom)"},
            {0xDBB89,"Bumper Cave (Top)"},
            {0xDBB8A,"Turtle Rock Isolated Ledge Entrance"},
            {0xDBB8B,"Dark Death Mountain Ledge (East)"},
            {0xDBB8C,"Fairy Ascension Cave (Bottom)"},
            {0xDBB8D,"Fairy Ascension Cave (Top)"},
            {0xDBB8E,"Spiral Cave (Bottom)"},
            {0xDBB8F,"Spiral Cave"},
            {0xDBB90,"7 Chest Cave (Bottom)"},
            {0xDBB91,"7 Chest Cave (Middle)"},
            {0xDBB92,"7 Chest Cave (Top)"},
            {0xDBB93,"Spectacle Rock Cave (Bottom)"},
            {0xDBB94,"Spectacle Rock Cave"},
            {0xDBB95,"Spectacle Rock Cave Peak"},
            {0xDBB96,"Agahnims Tower"},
            {0xDBB97,"Swamp Palace"},
            {0xDBB98,"Palace of Darkness"},
            {0xDBB99,"Misery Mire"},
            {0xDBB9A,"Skull Woods Second Section Door (West)"},
            {0xDBB9B,"Skull Woods Second Section Door (East)"},
            {0xDBB9C,"Skull Woods First Section Door"},
            {0xDBB9D,"Skull Woods Final Section"},
            {0xDBB9E,"Thieves Forest Hideout Stump"},
            {0xDBB9F,"Ice Palace"},
            {0xDBBA0,"Death Mountain Return Cave (West)"},
            {0xDBBA1,"Death Mountain Return Cave (East)"},
            {0xDBBA2,"Old Man House (Bottom)"},
            {0xDBBA3,"Old Man House (Top)"},
            {0xDBBA4,"Hyrule Castle Secret Entrance Stairs"},
            {0xDBBA5,"Tower of Hera"},
            {0xDBBA6,"Thieves Town"},
            {0xDBBA7,"Turtle Rock"},
            {0xDBBA8,"Pyramid Entrance"},
            {0xDBBA9,"Ganons Tower"},
            {0xDBBAA,"North Fairy Cave"},
            {0xDBBAB,"Kakariko Well Cave"},
            {0xDBBAC,"Hookshot Cave"},
            {0xDBBAD,"Hookshot Cave Back Entrance"},
            {0xDBBAE,"Lost Woods Gamble"},
            {0xDBBAF,"Dark Swamp Cave"},
            {0xDBBB0,"Snitch Lady (East)"},
            {0xDBBB1,"Snitch Lady (West)"},
            {0xDBBB2,"Sick Kids House"},
            {0xDBBB3,"Spike Cave"},
            {0xDBBB4,"Tavern (Front)"},
            {0xDBBB5,"Tavern North"},    // do not use buggy
            {0xDBBB6,"Bush Covered House"},
            {0xDBBB7,"Sahasrahlas Hut"},
            {0xDBBB8,"Kakariko Shop"},
            {0xDBBB9,"Chest Game"},
            {0xDBBBA,"Doorless Hut"},
            {0xDBBBB,"Library"},
            {0xDBBBC,"Light World Bomb Hut"},
            {0xDBBBD,"Chicken House"},
            {0xDBBBE,"Witch Hut"},
            {0xDBBC0,"Dam"},
            {0xDBBC1,"Mimic Cave Mirror Spot"},
            {0xDBBC2,"Hookshot Fairy"},
            {0xDBBC3,"Cave South of Haunted Grove"},
            {0xDBBC4,"Graveyard Cave"},
            {0xDBBC5,"Big Bomb Shop"},
            {0xDBBC6,"C-Shaped House"},
            {0xDBBC7,"Long Fairy Cave"},
            {0xDBBC8,"Dark Desert Fairy"},
            {0xDBBC9,"Dark World Lumberjack Shop"},
            {0xDBBCA,"Cave Shop (Lake Hylia)"},
            {0xDBBCB,"Archery Game"},
            {0xDBBCC,"Dark Sanctuary Hint"},
            {0xDBBCD,"Kings Grave"},
            {0xDBBCE,"Waterfall of Wishing"},
            {0xDBBCF,"Capacity Upgrade"},
            {0xDBBD0,"Lake Hylia Fairy"},
            {0xDBBD1,"Dark Desert Cave"},
            {0xDBBD2,"Dark World Shop"},
            {0xDBBD3,"Thiefs Hut"},
            {0xDBBD4,"Dark Desert Hint"},
            {0xDBBD5,"Pyramid Fairy"},
            {0xDBBD6,"Blacksmiths Hut"},
            {0xDBBD7,"Fortune Teller (Light)"},
            {0xDBBD8,"Fortune Teller (Dark)"},
            {0xDBBD9,"Kakariko Gamble Game"},
            {0xDBBDA,"Palace of Darkness Hint"},
            {0xDBBDB,"East Dark World Hint"},
            {0xDBBDC,"Dark Lake Hylia Ledge Hint"},
            {0xDBBDD,"Good Bee Cave"},
            {0xDBBDE,"Swamp Fairy"},
            {0xDBBDF,"Dark Lake Hylia Fairy"},
            {0xDBBE0,"Cave Shop (Dark Death Mountain)"},
            {0xDBBE1,"Dark World Potion Shop"},
            {0xDBBE2,"Dark Death Mountain Fairy"},
            {0xDBBE3,"Aginahs Cave"},
            {0xDBBE4,"Desert Fairy"},
            {0xDBBE5,"Lake Hylia Fortune Teller"},
            {0xDBBE6,"Dark Lake Hylia Shop"},
            {0xDBBE7,"Red Shield Shop"},
            {0xDBBE8,"Lumberjack House"},
            {0xDBBE9,"Bonk Fairy (Light)"},
            {0xDBBEA,"Bonk Fairy (Dark)"},
            {0xDBBEB,"50 Rupee Cave"},
            {0xDBBEC,"Bonk Rock Cave"},
            {0xDBBED,"20 Rupee Cave"},
            {0xDBBEE,"Dark Lake Hylia Ledge Spike Cave"},
            {0xDBBEF,"Mini Moldorm Cave"},
            {0xDBBF0,"Checkerboard Cave"},
            {0xDBBF1,"Dark World Hammer Peg Cave"},
            {0xDBBF2,"Ice Cave"},
            {0xDBBF3,"Dark Lake Hylia Ledge Fairy"},
        };

        public static string GetEntranceName(int entrance)
        {
            string ret = "";
            if(EntranceNames.TryGetValue(entrance, out ret))
            {
                return ret;
            }
            return null;
        }
        public readonly static Dictionary<int, string> EntranceNames = new Dictionary<int, string>()
        {
            { 0x00, "Link's House (middle spawn house)" },
            { 0x01, "Link's House (Door)" },
            { 0x02, "Sanctuary Exit (Main Entrance)" },     // 0x12),
            { 0x03, "Hyrule Castle Exit (West) (Left Entrance)" },  // 0x60),
            { 0x04, "Hyrule Castle Exit (South) (Main Entrance)" }, // 0x61),
            { 0x05, "Hyrule Castle Exit (East) (Right Entrance)" },  // 0x62),
            { 0x06, "Old Man Cave Exit (West) (Lower Entrance)" },   // 0xF0),
            { 0x07, "Old Man Cave Exit (East) (Upper Entrance)" },   // 0xF1),
            { 0x08, "Eastern Palace Exit (Main Entrance)" },        // 0xC9),
            { 0x09, "Desert Palace Exit (South) (Main Entrance)" }, // 0x84),
            { 0x0A, "Desert Palace Exit (East) (Right Entrance)" },  // 0x85),
            { 0x0B, "Desert Palace Exit (West) (Left Entrance)" },  // 0x83),
            { 0x0C, "Desert Palace Exit (North) (Boss Entrance)" }, // 0x63),
            { 0x0D, "Elder House Exit (West) (Left Entrance)" },    // 0xF2),
            { 0x0E, "Elder House Exit (East) (Right Entrnace)" },    // 0xF3),
            { 0x0F, "Two Brothers House Exit (West) (Left Entrance)" },     // 0xF4),
            { 0x10, "Two Brothers House Exit (East) (Right Entrance)" },     // 0xF5),
            { 0x11, "Bat Cave Exit (Main Entrance)" },      // 0xE3),
            { 0x12, "Lumberjack Tree Exit (Cave Entrance)" },       // 0xE2),
            { 0x13, "Dark Death Mountain Ascend Exit (Bottom)" },   // 0xF8),
            { 0x14, "Dark Death Mountain Ascend Exit (Top)" },      // 0xE8),
            { 0x15, "Turtle Rock Ledge Exit (West) (Bomb Cave Entrance 5 Lazer Eyes)" },      // 0x23),
            { 0x16, "Bumper Cave Exit (Bottom)" },  // 0xFB),
            { 0x17, "Bumper Cave Exit (Top)" },     // 0xEB),
            { 0x18, "Turtle Rock Isolated Ledge Exit (Bomb Cave Lazer Bridge)" },    // 0xD5),
            { 0x19, "Turtle Rock Ledge Exit (East) (Big Chest Entrance)" },      // 0x24),
            { 0x1A, "Fairy Ascension Cave Exit (Bottom) (Black Rocks Cave)" }, // 0xFD),
            { 0x1B, "Fairy Ascension Cave Exit (Top) (Middle via Drop?)" },    // 0xED),
            { 0x1C, "Spiral Cave Exit (Bottom)" },   // 0xFE),
            { 0x1D, "Spiral Cave Exit (Top) (Cave Entrance)" },     // 0xEE),
            { 0x1E, "7 Chest Cave Exit (Bottom) (LW Upside-down Cave 2 Entrance Hold Entrance)" }, // 0xFF),
            { 0x1F, "7 Chest Cave Exit (Middle) (LW Upside-down Cave 'Bottom' Entrance" }, // 0xEF),
            { 0x20, "7 Chest Cave Exit (Top) (LW Upside-down Cave Top Exit)" },    // 0xDF),
            { 0x21, "Spectacle Rock Cave Exit (Top Left via Drop [kikiskip])" },   // 0xF9),
            { 0x22, "Spectacle Rock Cave Exit (Top) (Top Middle via Drop to Item)" },     // 0xFA),
            { 0x23, "Spectacle Rock Cave Exit (Peak) (Top Middle Entrance)" },    // 0xEA),
            { 0x24, "Agahnims Tower Exit" },        // 0xE0),
            { 0x25, "Swamp Palace Exit" },  // 0x28),
            { 0x26, "Dark Palace Exit" },   // 0x4A),
            { 0x27, "Misery Mire Exit" },   // 0x98),
            { 0x28, "Skull Woods Second Section Exit (West) (Entrance with Bumper / Key Pot)" },     // 0x56),
            { 0x29, "Skull Woods Second Section Exit (East) (Statue Push Entrance)" },     // 0x57),
            { 0x2A, "Skull Woods First Section Exit (Big Chest Entrance)" },     // 0x58),
            { 0x2B, "Skull Woods Final Section Exit (Boss Entrance)" },     // 0x59),
            { 0x2C, "Thieves Forest Hideout Exit (Tree Entrance)" },        // 0xE1),
            { 0x2D, "Ice Palace Exit" },    // 0x0E),
            { 0x2E, "Death Mountain Return Cave Exit (West) (6 Holes Cave Exit)" },     // 0xE6),
            { 0x2F, "Death Mountain Return Cave Exit (East) (Long Ladder Cave)" },     // 0xE7),
            { 0x30, "Old Man House Exit (Bottom)" },        // 0xE4),
            { 0x31, "Old Man House Exit (Top)" },   // 0xE5),
            { 0x32, "Hyrule Castle Secret Entrance Exit (Courtyard Exit Door)" }, // 0x55),
            { 0x33, "Tower of Hera Exit" }, // 0x77),
            { 0x34, "Thieves Town Exit" },  // 0xDB),
            { 0x35, "Turtle Rock Exit (Front) (Main Entrance)" },   // 0xD6),
            { 0x36, "Pyramid Exit" },       // 0x10),
            { 0x37, "Ganons Tower Exit" },  // 0x0C),
            { 0x38, "North Fairy Cave Exit (Right of Cemetary Fairy Cave Entrance)" },      // 0x08),
            { 0x39, "Kakariko Well Exit (Cave Exit)" }, // 0x2F),
            { 0x3A, "Hookshot Cave Exit (South) (Under Rock Entrance)" }, // 0x3C),
            { 0x3B, "Hookshot Cave Exit (North) (Floating Island Exit)" }, // 0x2C),
            { 0x3C, "Lost Woods Gamble" },
            { 0x3D, "Dark Swamp Cave (Hype Cave)" },
            { 0x3E, "Snitch Lady (East) (Left side in Room Map [logically swapped])" },
            { 0x3F, "Snitch Lady (West) (Right side in Room Map [logically swapped])" },
            { 0x40, "Sick Kids House" },
            { 0x41, "Spike Cave" },
            { 0x42, "Tavern (Front)" },
            { 0x43, "Tavern (Back Door)" },
            { 0x44, "Bush Covered House (Kakariko Bushes House)" },
            { 0x45, "Sahasrahlas Hut" },
            { 0x46, "Kakariko Shop" },
            { 0x47, "Chest Game (DW)" },
            { 0x48, "Doorless Hut (DW)" },
            { 0x49, "Library" },
            { 0x4A, "Light World Bomb Hut (Doorless Bomb House)" },
            { 0x4B, "Chicken House" },
            { 0x4C, "Witch Hut (Potion Shop)" },
            { 0x4D, "Aginahs Cave" },
            { 0x4E, "Dam" },
            { 0x4F, "Mimic Cave" },
            { 0x50, "Hookshot Fairy (East DM Behind 2 Dark Rocks)" },
            { 0x51, "Cave South of Haunted Grove" },
            { 0x52, "Graveyard Cave (Mirror Cave)" },
            { 0x53, "Big Bomb Shop" },
            { 0x54, "C-Shaped House" },
            { 0x55, "Long Fairy Cave (Near flute #5)" },
            { 0x56, "Good Bee Cave (Ice Rod Right Entrance)" },
            { 0x57, "Red Shield Shop (Shop West of Pyramid)" },
            { 0x58, "Cave Shop (Lake Hylia Shop)" },
            { 0x59, "Archery Game" },
            { 0x5A, "Dark Sanctuary Hint" },
            { 0x5B, "Kings Grave (Push Grave)" },
            { 0x5C, "Waterfall of Wishing (Outside Zora's Domain)" },
            { 0x5D, "Capacity Upgrade (Lake Hylia Island Cave)" },
            { 0x5E, "Healer Fairy (South of Eastern Palace Area)" },
            { 0x5F, "Dark Desert Cave (Left of Mire Entrance 2 Chests)" },
            { 0x60, "Dark World Shop (Behind Pegs in Outcast Village)" },
            { 0x61, "Thiefs Hut (Blind's House)" },
            { 0x62, "Dark Desert Hint (Cave in Mire Area)" },
            { 0x63, "Pyramid Fairy (Fat Fairy)" },
            { 0x64, "Blacksmiths Hut" },
            { 0x65, "Fortune Teller (Light)" },
            { 0x66, "Fortune Teller (Dark)" },
            { 0x67, "Kakariko Gamble Game (3 Chest Game)" },
            { 0x68, "Palace of Darkness Hint" },
            { 0x69, "East Dark World Hint (DW Flute #5 Cave)" },
            { 0x6A, "Dark Lake Hylia Ledge Hint (DW Ice Rod Cave)" },
            { 0x6B, "Lumberjack House" },
            { 0x6C, "Mini Moldorm Cave" },
            { 0x6D, "50 Rupee Cave (Big Lift Rock Before Desert)" },
            { 0x6E, "Bonk Rock Cave (Next to Sanctuary)" },
            { 0x6F, "20 Rupee Cave (Big Lift Rock Outside Ice Rod Cave)" },
            { 0x70, "Dark Lake Hylia Ledge Spike Cave (DW Big Lift Rock Outside Ice Rod Cave)" },
            { 0x71, "Bonk Fairy (Bonk Rocks West of Link's House)" },
            { 0x72, "Checkerboard Cave" },
            { 0x73, "Zeld's Jail Cell (Special Entrance)" },
            { 0x74, "Hyrule Castle Entrance (Special Entrance)" },
            { 0x75, "Agahnim Teleport Room (Special Entrance)" },
            { 0x76, "Skull Woods First Section (Top) (Drop Entrance)" },
            { 0x77, "Skull Woods First Section (Left) (Drop Entrance)" },
            { 0x78, "Skull Woods First Section (Right) (Drop Entrance)" },
            { 0x79, "Skull Woods Second Section (Drop Entrance)" },
            { 0x7A, "Thieves Forest Hideout (top) (Drop Entrance)" },
            { 0x7B, "Pyramid (Drop Entrance)" },
            { 0x7C, "North Fairy Cave (Bush East of Cemetary) (Drop Entrance)" },
            { 0x7D, "Hyrule Castle Secret Entrance (Bush Entrance) (Drop Entrance)" },
            { 0x7E, "Bat Cave (right) (Drop Entrance)" },
            { 0x7F, "Lumberjack Tree (top) (Drop Entrance)" },
            { 0x80, "Kakariko Well (top) (Drop Entrance)" },
            { 0x81, "Sewer Drop (Graveyard Entrance) (Drop Entrance)" },
            { 0x82, "Houlihan Room (Drop Entrance) "},
            { 0x83, "Dark World Hammer Peg Cave" },
            { 0x84, "Ice Cave (Ice Rod Cave Left Bomb Entrance)" },
            /*
            { 0x00, "00 Link's house (middle spawn house)" },
            { 0x01, "01 Link's house (Door)" },
            { 0x02, "02 Sanctuary (Main Entrance)" },
            { 0x03, "03 Hyrule Castle (Left Entrance)" },
            { 0x04, "04 Hyrule Castle (Main Entrance)" },
            { 0x05, "05 Hyrule Castle (Right Entrance)" },
            { 0x06, "06 Old man cave (Lower Entrance)" },
            { 0x07, "07 Old man cave (DM Entrance)" },
            { 0x08, "08 Eastern Palace (Main Entrance)" },
            { 0x09, "09 Desert Palace (Main Entrance)" },
            { 0x0A, "0A Desert Palace (Right Entrance)" },
            { 0x0B, "0B Desert Palace (Left Entrance)" },
            { 0x0C, "0C Desert Palace (Boss Entrance)" },
            { 0x0D, "0D Kakariko double house (Left Entrance)" },
            { 0x0E, "0E Kakariko double house (Right Entrance)" },
            { 0x0F, "0F Angry brother house (Left Entrance)" },
            { 0x10, "10 Angry brother house (Right Entrance)" },
            { 0x11, "11 Smith Cave (Main Entrance)" },
            { 0x12, "12 Agahnim Tree Cave (Cave Entrance)" },
            { 0x13, "13 (DW)DMR Bottom Left (Cave Entrance)" },
            { 0x14, "14 (DW)DMR Top cave" },
            { 0x15, "15 (DW)Turtle Rock Laser eyes (Bomb Cave Entrance)" },
            { 0x16, "16 (DW)Bumper Cave Bottom Entrance (Cave Entrance)" },
            { 0x17, "17 (DW)Bumper Cave Top Entrance (Cave Entrance)" },
            { 0x18, "18 (DW)Turtle Rock Laser Skip (Bomb Cave Entrance)" },
            { 0x19, "19 (DW)Turtle Rock Big Chest (Cave Entrance)" },
            { 0x1A, "1A (LW)DMR Black rocks cave (Cave Entrance)" },
            { 0x1B, "1B (LW)DMR Middle cave via drop (Cave Entrance)" },
            { 0x1C, "1C (LW)DMR Spiral Cave (Cave Exit)" },
            { 0x1D, "1D (LW)DMR Spiral Cave via drop (Cave Entrance)" },
            { 0x1E, "1E (LW)DMR Bottom Right 2 Caves (Cave Entrance)" },
            { 0x1F, "1F (LW)DMR Bottom Right (Cave Entrance)" },
            { 0x20, "20 (LW)DMR Top Right (Cave Entrance)" },
            { 0x21, "21 (LW)DML Top Left via drop (kikiskip) (Cave Entrance)" },
            { 0x22, "22 (LW)DML Top Middle via drop (Cave Entrance)" },
            { 0x23, "23 (LW)DML Top Middle Spectacle rock (Cave Entrance)" },
            { 0x24, "24 (LW)Agahnim Tower" },
            { 0x25, "25 (DW)Swamp Palace" },
            { 0x26, "26 (DW)Palace Of Darkness" },
            { 0x27, "27 (DW)Misery Mire" },
            { 0x28, "28 (DW)Skull Woods (Entrance with Bumper / Key Pot)" },
            { 0x29, "29 (DW)Skull Woods (Statue Push Entrance)" },
            { 0x2A, "2A (DW)Skull Woods (Big Chest Entrance)" },
            { 0x2B, "2B (DW)Skull Woods (Boss part Entrance)" },
            { 0x2C, "2C (LW)Woods Heart Piece (Tree Entrance)" },
            { 0x2D, "2D (DW)Ice Palace Entrance" },
            { 0x2E, "2E (LW)6 holes cave exit of DM" },
            { 0x2F, "2F (LW)DML Long ladder cave" },
            { 0x30, "30 (LW)DML Old Man (healing) cave" },
            { 0x31, "31 (LW)DML Bottom Cave (old man exit)" },
            { 0x32, "32 (LW)Secret bush entrance (Door)" },
            { 0x33, "33 (LW)Tower of Hera" },
            { 0x34, "34 (DW)Thieves Town" },
            { 0x35, "35 (DW)Turtle Rock (Main Entrance)" },
            { 0x36, "36 (DW)Pyramid Entrance between 2 statue" },
            { 0x37, "37 (DW)Ganon's Tower" },
            { 0x38, "38 (LW)Right side of Cemetary (cave entrance)" },
            { 0x39, "39 (LW)Kakariko Well (Door)" },
            { 0x3A, "3A (DW)DMR Top Right (under rock)" },
            { 0x3B, "3B (DW)DMR Door leading to floating island" },
            { 0x3C, "3C (DW)SHOP" },
            { 0x3D, "3D (DW)Npc cave top right of swamp" },
            { 0x3E, "3E (LW)Kakariko Right House" },
            { 0x3F, "3F (LW)Kakariko Left House" },
            { 0x40, "40 (LW)Kakariko Sickboy house" },
            { 0x41, "41 (LW)DML Spike cave" },
            { 0x42, "42 (LW)Tavern Main Entrance" },
            { 0x43, "43 (LW)Tavern Back Entrance" },
            { 0x44, "44 (LW)Kakariko Bushes House" },
            { 0x45, "45 (LW)Sarahsrala's Hut" },
            { 0x46, "46 (LW)Kakariko SHOP" },
            { 0x47, "47 (DW)Chest Minigame" },
            { 0x48, "48 (DW)300 rupees,Redboom hut" },
            { 0x49, "49 (LW)Library" },
            { 0x4A, "4A (LW)Secret bombhouse Kakariko" },
            { 0x4B, "4B (LW)Chicken House" },
            { 0x4C, "4C (LW)Witch Potion Shop" },
            { 0x4D, "4D (LW)Desert Aginah Cave" },
            { 0x4E, "4E (LW)DAM Entrance" },
            { 0x4F, "4F (LW)DMR Mimic cave" },
            { 0x50, "50 (LW)DMR Fairyhookshot cave" },
            { 0x51, "51 (LW)Mirror cave under flute location" },
            { 0x52, "52 (LW)Cemetary Mirror Cave" },
            { 0x53, "53 (DW)Link's House Bomb shop" },
            { 0x54, "54 (DW)C-Shaped House Kakariko" },
            { 0x55, "55 (DW)FairyCave" },
            { 0x56, "56 (LW)Ice rod cave (Right cave)" },
            { 0x57, "57 (DW)Lonely Shop West of pyramid" },
            { 0x58, "58 (LW/DW)Cave SHOPS" },
            { 0x59, "59 (DW)Archery Game" },
            { 0x5A, "5A (DW)Sanctuary Cave" },
            { 0x5B, "5B (LW)Cape Grave Entrance" },
            { 0x5C, "5C (LW)Waterfall Pond" },
            { 0x5D, "5D (LW)Arrow/Bombs Pond" },
            { 0x5E, "5E  All Big Fairy Rooms" },
            { 0x5F, "5F (DW)Left Mire Entrance (2 chest)" },
            { 0x60, "60 (DW)SHOPS" },
            { 0x61, "61 (LW)Thieves Hut" },
            { 0x62, "62 (DW)Desert Cave" },
            { 0x63, "63 (DW)Pyramid Pond" },
            { 0x64, "64 (LW)Smith House" },
            { 0x65, "65 (LW)Fortune Teller" },
            { 0x66, "66 (DW)Fortune Teller" },
            { 0x67, "67 (LW?)3Chest minigame" },
            { 0x68, "68 (DW)MiniTree? House (Palace of darkness Area)" },
            { 0x69, "69 (DW)Flute #5 Cave" },
            { 0x6A, "6A (??)NPC Cave" },
            { 0x6B, "6B (LW)SHOP" },
            { 0x6C, "6C (LW)Minimoldorm cave hylia lake" },
            { 0x6D, "6D (LW)Thief Cave" },
            { 0x6E, "6E (LW)Sanctuary under rock cave" },
            { 0x6F, "6F (LW)Thief Cave near ice rod" },
            { 0x70, "70 (??)Unknow Spike cave" },
            { 0x71, "71 (LW)link's fairy cave" },
            { 0x72, "72 Desert mirror block maze" },
            { 0x73, "73 Zelda Cell (Spawn beside zelda) (intro entrance)" },
            { 0x74, "74 Hyrule Castle Throne Room (intro entrance)" },
            { 0x75, "75 Agahnim Torture Room (intro entrance)" },
            { 0x76, "76 Skull Woods big chest (Drop Entrance)" },
            { 0x77, "77 Skull Woods left hole (Drop Entrance)" },
            { 0x78, "78 Skull Woods right hole (Drop Entrance)" },
            { 0x79, "79 Skull Woods lost hole? (Drop Entrance)" },
            { 0x7A, "7A Forest Heart Piece middle bush (Drop Entrance)" },
            { 0x7B, "7B Ganon (Drop Entrance)" },
            { 0x7C, "7C bush right side of cemetary (Drop Entrance)" },
            { 0x7D, "7D Escape secret entrance bush (Drop Entrance)" },
            { 0x7E, "7E Smith powder (Drop Entrance)" },
            { 0x7F, "7F Lumberjack tree (Drop Entrance)" },
            { 0x80, "80 Kakariko Well (Drop Entrance)" },
            { 0x81, "81 Escape Grave (Drop Entrance)" },
            { 0x82, "82 Houlihan Cave (Drop Entrance)" },
            { 0x83, "83 Smith Pegs Cave" },
            { 0x84, "84 Ice Rod Cave (Left Entrance)" },
            */
        };
    }
}
