using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EnemizerLibrary
{
    public class EntranceConstants
    {
        public static string GetEntranceName(int entrance)
        {
            string ret = "";
            if(EntranceNames.TryGetValue(entrance, out ret))
            {
                return ret;
            }
            return null;
        }
        public readonly static Dictionary<int, string> EntranceNames = new Dictionary<int, string>()
        {
            { 0x00, "00 Link's house (middle spawn house)" },
            { 0x01, "01 Link's house (Door)" },
            { 0x02, "02 Sanctuary (Main Entrance)" },
            { 0x03, "03 Hyrule Castle (Left Entrance)" },
            { 0x04, "04 Hyrule Castle (Main Entrance)" },
            { 0x05, "05 Hyrule Castle (Right Entrance)" },
            { 0x06, "06 Old man cave (Lower Entrance)" },
            { 0x07, "07 Old man cave (DM Entrance)" },
            { 0x08, "08 Eastern Palace (Main Entrance)" },
            { 0x09, "09 Desert Palace (Main Entrance)" },
            { 0x0A, "0A Desert Palace (Right Entrance)" },
            { 0x0B, "0B Desert Palace (Left Entrance)" },
            { 0x0C, "0C Desert Palace (Boss Entrance)" },
            { 0x0D, "0D Kakariko double house (Left Entrance)" },
            { 0x0E, "0E Kakariko double house (Right Entrance)" },
            { 0x0F, "0F Angry brother house (Left Entrance)" },
            { 0x10, "10 Angry brother house (Right Entrance)" },
            { 0x11, "11 Smith Cave (Main Entrance)" },
            { 0x12, "12 Agahnim Tree Cave (Cave Entrance)" },
            { 0x13, "13 (DW)DMR Bottom Left (Cave Entrance)" },
            { 0x14, "14 (DW)DMR Top cave" },
            { 0x15, "15 (DW)Turtle Rock Laser eyes (Bomb Cave Entrance)" },
            { 0x16, "16 (DW)Bumper Cave Bottom Entrance (Cave Entrance)" },
            { 0x17, "17 (DW)Bumper Cave Top Entrance (Cave Entrance)" },
            { 0x18, "18 (DW)Turtle Rock Laser Skip (Bomb Cave Entrance)" },
            { 0x19, "19 (DW)Turtle Rock Big Chest (Cave Entrance)" },
            { 0x1A, "1A (LW)DMR Black rocks cave (Cave Entrance)" },
            { 0x1B, "1B (LW)DMR Middle cave via drop (Cave Entrance)" },
            { 0x1C, "1C (LW)DMR Spiral Cave (Cave Exit)" },
            { 0x1D, "1D (LW)DMR Spiral Cave via drop (Cave Entrance)" },
            { 0x1E, "1E (LW)DMR Bottom Right 2 Caves (Cave Entrance)" },
            { 0x1F, "1F (LW)DMR Bottom Right (Cave Entrance)" },
            { 0x20, "20 (LW)DMR Top Right (Cave Entrance)" },
            { 0x21, "21 (LW)DML Top Left via drop (kikiskip) (Cave Entrance)" },
            { 0x22, "22 (LW)DML Top Middle via drop (Cave Entrance)" },
            { 0x23, "23 (LW)DML Top Middle Spectacle rock (Cave Entrance)" },
            { 0x24, "24 (LW)Agahnim Tower" },
            { 0x25, "25 (DW)Swamp Palace" },
            { 0x26, "26 (DW)Palace Of Darkness" },
            { 0x27, "27 (DW)Misery Mire" },
            { 0x28, "28 (DW)Skull Woods (Entrance with Bumper / Key Pot)" },
            { 0x29, "29 (DW)Skull Woods (Statue Push Entrance)" },
            { 0x2A, "2A (DW)Skull Woods (Big Chest Entrance)" },
            { 0x2B, "2B (DW)Skull Woods (Boss part Entrance)" },
            { 0x2C, "2C (LW)Woods Heart Piece (Tree Entrance)" },
            { 0x2D, "2D (DW)Ice Palace Entrance" },
            { 0x2E, "2E (LW)6 holes cave exit of DM" },
            { 0x2F, "2F (LW)DML Long ladder cave" },
            { 0x30, "30 (LW)DML Old Man (healing) cave" },
            { 0x31, "31 (LW)DML Bottom Cave (old man exit)" },
            { 0x32, "32 (LW)Secret bush entrance (Door)" },
            { 0x33, "33 (LW)Tower of Hera" },
            { 0x34, "34 (DW)Thieves Town" },
            { 0x35, "35 (DW)Turtle Rock (Main Entrance)" },
            { 0x36, "36 (DW)Pyramid Entrance between 2 statue" },
            { 0x37, "37 (DW)Ganon's Tower" },
            { 0x38, "38 (LW)Right side of Cemetary (cave entrance)" },
            { 0x39, "39 (LW)Kakariko Well (Door)" },
            { 0x3A, "3A (DW)DMR Top Right (under rock)" },
            { 0x3B, "3B (DW)DMR Door leading to floating island" },
            { 0x3C, "3C (DW)SHOP" },
            { 0x3D, "3D (DW)Npc cave top right of swamp" },
            { 0x3E, "3E (LW)Kakariko Right House" },
            { 0x3F, "3F (LW)Kakariko Left House" },
            { 0x40, "40 (LW)Kakariko Sickboy house" },
            { 0x41, "41 (LW)DML Spike cave" },
            { 0x42, "42 (LW)Tavern Main Entrance" },
            { 0x43, "43 (LW)Tavern Back Entrance" },
            { 0x44, "44 (LW)Kakariko Bushes House" },
            { 0x45, "45 (LW)Sarahsrala's Hut" },
            { 0x46, "46 (LW)Kakariko SHOP" },
            { 0x47, "47 (DW)Chest Minigame" },
            { 0x48, "48 (DW)300 rupees,Redboom hut" },
            { 0x49, "49 (LW)Library" },
            { 0x4A, "4A (LW)Secret bombhouse Kakariko" },
            { 0x4B, "4B (LW)Chicken House" },
            { 0x4C, "4C (LW)Witch Potion Shop" },
            { 0x4D, "4D (LW)Desert Aginah Cave" },
            { 0x4E, "4E (LW)DAM Entrance" },
            { 0x4F, "4F (LW)DMR Mimic cave" },
            { 0x50, "50 (LW)DMR Fairyhookshot cave" },
            { 0x51, "51 (LW)Mirror cave under flute location" },
            { 0x52, "52 (LW)Cemetary Mirror Cave" },
            { 0x53, "53 (DW)Link's House Bomb shop" },
            { 0x54, "54 (DW)C-Shaped House Kakariko" },
            { 0x55, "55 (DW)FairyCave" },
            { 0x56, "56 (LW)Ice rod cave (Right cave)" },
            { 0x57, "57 (DW)Lonely Shop West of pyramid" },
            { 0x58, "58 (LW/DW)Cave SHOPS" },
            { 0x59, "59 (DW)Archery Game" },
            { 0x5A, "5A (DW)Sanctuary Cave" },
            { 0x5B, "5B (LW)Cape Grave Entrance" },
            { 0x5C, "5C (LW)Waterfall Pond" },
            { 0x5D, "5D (LW)Arrow/Bombs Pond" },
            { 0x5E, "5E  All Big Fairy Rooms" },
            { 0x5F, "5F (DW)Left Mire Entrance (2 chest)" },
            { 0x60, "60 (DW)SHOPS" },
            { 0x61, "61 (LW)Thieves Hut" },
            { 0x62, "62 (DW)Desert Cave" },
            { 0x63, "63 (DW)Pyramid Pond" },
            { 0x64, "64 (LW)Smith House" },
            { 0x65, "65 (LW)Fortune Teller" },
            { 0x66, "66 (DW)Fortune Teller" },
            { 0x67, "67 (LW?)3Chest minigame" },
            { 0x68, "68 (DW)MiniTree? House (Palace of darkness Area)" },
            { 0x69, "69 (DW)Flute #5 Cave" },
            { 0x6A, "6A (??)NPC Cave" },
            { 0x6B, "6B (LW)SHOP" },
            { 0x6C, "6C (LW)Minimoldorm cave hylia lake" },
            { 0x6D, "6D (LW)Thief Cave" },
            { 0x6E, "6E (LW)Sanctuary under rock cave" },
            { 0x6F, "6F (LW)Thief Cave near ice rod" },
            { 0x70, "70 (??)Unknow Spike cave" },
            { 0x71, "71 (LW)link's fairy cave" },
            { 0x72, "72 Desert mirror block maze" },
            { 0x73, "73 Zelda Cell (Spawn beside zelda) (intro entrance)" },
            { 0x74, "74 Hyrule Castle Throne Room (intro entrance)" },
            { 0x75, "75 Agahnim Torture Room (intro entrance)" },
            { 0x76, "76 Skull Woods big chest (Drop Entrance)" },
            { 0x77, "77 Skull Woods left hole (Drop Entrance)" },
            { 0x78, "78 Skull Woods right hole (Drop Entrance)" },
            { 0x79, "79 Skull Woods lost hole? (Drop Entrance)" },
            { 0x7A, "7A Forest Heart Piece middle bush (Drop Entrance)" },
            { 0x7B, "7B Ganon (Drop Entrance)" },
            { 0x7C, "7C bush right side of cemetary (Drop Entrance)" },
            { 0x7D, "7D Escape secret entrance bush (Drop Entrance)" },
            { 0x7E, "7E Smith powder (Drop Entrance)" },
            { 0x7F, "7F Lumberjack tree (Drop Entrance)" },
            { 0x80, "80 Kakariko Well (Drop Entrance)" },
            { 0x81, "81 Escape Grave (Drop Entrance)" },
            { 0x82, "82 Houlihan Cave (Drop Entrance)" },
            { 0x83, "83 Smith Pegs Cave" },
            { 0x84, "84 Ice Rod Cave (Left Entrance)" },
        };
    }
}
