using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EnemizerLibrary
{
    public class ExitConstants
    {
        public static string GetExitAreaName(int address)
        {
            string ret = "";
            if (ExitAreaNames.TryGetValue(address, out ret))
            {
                return ret;
            }
            return null;
        }

        public readonly static Dictionary<int, string> ExitAreaNames = new Dictionary<int, string>()
        {
            { 0x15B8C, "Link's House" },
            { 0x15B8D, "Sanctuary" },
            { 0x15B8E, "Hyrule Castle Entrance (West)" },
            { 0x15B8F, "Hyrule Castle Entrance (South)" },
            { 0x15B90, "Hyrule Castle Entrance (East)" },
            { 0x15B91, "Entrance to Zora's Domain" },
            { 0x15B92, "Warp to Pyramid After Defeating Agahnim" },
            { 0x15B93, "Old Man Cave (West)" },
            { 0x15B94, "Old Man Cave (East)" },
            { 0x15B95, "Eastern Palace" },
            { 0x15B96, "Desert Palace Entrance (South)" },
            { 0x15B97, "Desert Palace Entrance (East)" },
            { 0x15B98, "Desert Palace Entrance (West)" },
            { 0x15B99, "Desert Palace Entrance (North)" },
            { 0x15B9A, "Elder House (West)" },
            { 0x15B9B, "Elder House (East)" },
            { 0x15B9C, "Two Brothers House (West)" },
            { 0x15B9D, "Two Brothers House (East)" },
            { 0x15B9E, "Bat Cave Cave" },
            { 0x15B9F, "Lumberjack Tree Cave" },
            { 0x15BA0, "Dark Death Mountain Ascend (Bottom)" },
            { 0x15BA1, "Dark Death Mountain Ascend (Top)" },
            { 0x15BA2, "Dark Death Mountain Ledge (West)" },
            { 0x15BA3, "Bumper Cave (Bottom)" },
            { 0x15BA4, "Bumper Cave (Top)" },
            { 0x15BA5, "Turtle Rock Isolated Ledge Entrance" },
            { 0x15BA6, "Dark Death Mountain Ledge (East)" },
            { 0x15BA7, "Fairy Ascension Cave (Bottom)" },
            { 0x15BA8, "Fairy Ascension Cave (Top)" },
            { 0x15BA9, "Spiral Cave (Bottom)" },
            { 0x15BAA, "Spiral Cave" },
            { 0x15BAB, "7 Chest Cave (Bottom)" },
            { 0x15BAC, "7 Chest Cave (Middle)" },
            { 0x15BAD, "7 Chest Cave (Top)" },
            { 0x15BAE, "Spectacle Rock Cave (Bottom)" },
            { 0x15BAF, "Spectacle Rock Cave" },
            { 0x15BB0, "Spectacle Rock Cave Peak" },
            { 0x15BB1, "Agahnims Tower" },
            { 0x15BB2, "Swamp Palace" },
            { 0x15BB3, "Palace of Darkness" },
            { 0x15BB4, "Misery Mire" },
            { 0x15BB5, "Skull Woods Second Section Door (West)" },
            { 0x15BB6, "Skull Woods Second Section Door (East)" },
            { 0x15BB7, "Skull Woods First Section Door" },
            { 0x15BB8, "Skull Woods Final Section" },
            { 0x15BB9, "Tower of Hera" },
            { 0x15BBA, "Ice Palace" },
            { 0x15BBB, "Death Mountain Return Cave (West)" },
            { 0x15BBC, "Death Mountain Return Cave (East)" },
            { 0x15BBD, "Old Man House (Bottom)" },
            { 0x15BBE, "Old Man House (Top)" },
            { 0x15BBF, "Hyrule Castle Secret Entrance Stairs" },
            { 0x15BC0, "Turtle Rock" },
            { 0x15BC1, "Thieves Town" },
            { 0x15BC2, "Thieves Forest Hideout Stump" },
            { 0x15BC3, "Pyramid Entrance" },
            { 0x15BC4, "Ganons Tower" },
            { 0x15BC5, "North Fairy Cave" },
            { 0x15BC6, "Kakariko Well Cave" },
            { 0x15BC7, "Hookshot Cave" },
            { 0x15BC8, "Hookshot Cave Back Entrance" },
            { 0x15BC9, "Link's House (from Houlihan)" },
            /*
             * 0x15BCA-0x15BDA seem to be special rooms/areas
             * credits : castle gate, lumberjack, deathmountain, woods, kakariko, witch, zora,desert
             */
        };

        public static string GetExitRoomName(int roomid)
        {
            string ret = "";
            if (ExitRoomNames.TryGetValue(roomid, out ret))
            {
                return ret;
            }
            return null;
        }
        public readonly static Dictionary<int, string> ExitRoomNames = new Dictionary<int, string>()
        {
            {0x00,"Pyramid (Drop Entrance)"},
            {0x08,"North Fairy Cave Exit"},
            {0x0C,"Ganons Tower Exit"},
            {0x0E,"Ice Palace Exit"},
            {0x10,"Pyramid Exit"},
            {0x11,"Sewer Drop (Drop Entrance)"},
            {0x12,"Sanctuary Exit"},
            {0x18,"North Fairy Cave (Drop Entrance)"},
            {0x23,"Turtle Rock Ledge Exit (West)"},
            {0x24,"Turtle Rock Ledge Exit (East)"},
            {0x28,"Swamp Palace Exit"},
            {0x2C,"Hookshot Cave Exit (North)"},
            {0x2F,"Kakariko Well Exit / Kakariko Well (top) (Drop Entrance)"},
            //{0x2F,"Kakariko Well (top) (Drop Entrance)"},
            {0x30,"Agahnim Teleport Room (Special Entrance)"},
            {0x3C,"Hookshot Cave Exit (South)"},
            {0x4A,"Dark Palace Exit"},
            {0x55,"Hyrule Castle Secret Entrance Exit / Hyrule Castle Secret Entrance (Drop Entrance)"},
            //{0x55,"Hyrule Castle Secret Entrance (Drop Entrance)"},
            {0x56,"Skull Woods Second Section Exit (West) / Skull Woods Second Section (Drop Entrance)"},
            //{0x56,"Skull Woods Second Section (Drop Entrance)"},
            {0x57,"Skull Woods Second Section Exit (East)"},
            {0x58,"Skull Woods First Section Exit / Skull Woods First Section (Top) (Drop Entrance)"},
            //{0x58,"Skull Woods First Section (Top) (Drop Entrance)"},
            {0x59,"Skull Woods Final Section Exit"},
            {0x60,"Hyrule Castle Exit (West)"},
            {0x61,"Hyrule Castle Exit (South) / Hyrule Castle Entrance (Special Entrance)"},
            //{0x61,"Hyrule Castle Entrance (Special Entrance)"},
            {0x62,"Hyrule Castle Exit (East)"},
            {0x63,"Desert Palace Exit (North)"},
            {0x67,"Skull Woods First Section (Left) (Drop Entrance)"},
            {0x68,"Skull Woods First Section (Right) (Drop Entrance)"},
            {0x77,"Tower of Hera Exit"},
            {0x80,"Zelda Cell (Spawn Beside Zelda) (Special Entrance)"},
            {0x83,"Desert Palace Exit (West)"},
            {0x84,"Desert Palace Exit (South)"},
            {0x85,"Desert Palace Exit (East)"},
            {0x98,"Misery Mire Exit"},
            {0xC9,"Eastern Palace Exit"},
            {0xD5,"Turtle Rock Isolated Ledge Exit"},
            {0xD6,"Turtle Rock Exit (Front)"},
            {0xDB,"Thieves Town Exit"},
            {0xDF,"7 Chest Cave Exit (Top)"},
            {0xE0,"Agahnims Tower Exit"},
            {0xE1,"Thieves Forest Hideout Exit / Thieves Forest Hideout (top) (Drop Entrance)"},
            //{0xE1,"Thieves Forest Hideout (top) (Drop Entrance)"},
            {0xE2,"Lumberjack Tree Exit / Lumberjack Tree (top) (Drop Entrance)"},
            //{0xE2,"Lumberjack Tree (top) (Drop Entrance)"},
            {0xE3,"Bat Cave Exit / Bat Cave (right) (Drop Entrance)"},
            //{0xE3,"Bat Cave (right) (Drop Entrance)"},
            {0xE4,"Old Man House Exit (Bottom)"},
            {0xE5,"Old Man House Exit (Top)"},
            {0xE6,"Death Mountain Return Cave Exit (West)"},
            {0xE7,"Death Mountain Return Cave Exit (East)"},
            {0xE8,"Dark Death Mountain Ascend Exit (Top)"},
            {0xEA,"Spectacle Rock Cave Exit (Peak)"},
            {0xEB,"Bumper Cave Exit (Top)"},
            {0xED,"Fairy Ascension Cave Exit (Top)"},
            {0xEE,"Spiral Cave Exit (Top)"},
            {0xEF,"7 Chest Cave Exit (Middle)"},
            {0xF0,"Old Man Cave Exit (West)"},
            {0xF1,"Old Man Cave Exit (East)"},
            {0xF2,"Elder House Exit (West)"},
            {0xF3,"Elder House Exit (East)"},
            {0xF4,"Two Brothers House Exit (West)"},
            {0xF5,"Two Brothers House Exit (East)"},
            {0xF8,"Dark Death Mountain Ascend Exit (Bottom)"},
            {0xF9,"Spectacle Rock Cave Exit"},
            {0xFA,"Spectacle Rock Cave Exit (Top)"},
            {0xFB,"Bumper Cave Exit (Bottom)"},
            {0xFD,"Fairy Ascension Cave Exit (Bottom)"},
            {0xFE,"Spiral Cave Exit"},
            {0xFF,"7 Chest Cave Exit (Bottom)"},

            {0x100,"Lost Woods Gamble"},
            {0x101,"Snitch Lady (East) / Snitch Lady (West)"},
            //{ 0x101, "Snitch Lady (West)" },
            {0x102,"Sick Kids House"},
            {0x103,"Bush Covered House / Tavern (Front) / Tavern (Back Door)"},
            //{0x103,"Tavern (Front)"},
            //{0x103,"Tavern (Back Door)"},
            {0x104,"Houlihan Cave (Drop Entrance)"},
            {0x105,"Sahasrahlas Hut"},
            {0x106,"Chest Game / Doorless Hut"},
            //{0x106,"Doorless Hut"},
            {0x107,"Library / Light World Bomb Hut"},
            //{0x107,"Light World Bomb Hut"},
            {0x108,"Chicken House"},
            {0x109,"Witch Hut"},
            {0x10A,"Aginahs Cave"},
            {0x10B,"Dam"},
            {0x10C,"Hookshot Fairy / Mimic Cave"},
            //{0x10C,"Mimic Cave"},
            {0x10D,"Dark Desert Cave"},
            {0x10E,"Dark Lake Hylia Ledge Hint / East Dark World Hint"},
            //{0x10E,"East Dark World Hint"},
            {0x10F,"Dark World Shop"},
            {0x110,"Red Shield Shop"},
            {0x111,"Archery Game"},
            {0x112,"Cave Shop / Dark Sanctuary Hint"},
            //{0x112,"Dark Sanctuary Hint"},
            {0x113,"Kings Grave"},
            {0x114,"Dark Desert Hint / Waterfall of Wishing"},
            //{0x114,"Waterfall of Wishing"},
            {0x115,"Capacity Upgrade / Healer Fairy"},
            //{0x115,"Healer Fairy"},
            {0x116,"Pyramid Fairy"},
            {0x117,"Spike Cave"},
            {0x118,"Kakariko Gamble Game"},
            {0x119,"Thiefs Hut"},
            {0x11A,"Palace of Darkness Hint"},
            {0x11B,"Cave South of Haunted Grove / Graveyard Cave (Mirror Cave)"},
            //{0x11B,"Graveyard Cave"},
            {0x11C,"Big Bomb Shop / C-Shaped House"},
            //{0x11C,"C-Shaped House"},
            {0x11E,"Dark Swamp Cave / Long Fairy Cave"},
            //{0x11E,"Long Fairy Cave"},
            {0x11F,"Kakariko Shop / Lumberjack House"},
            //{0x11F,"Lumberjack House"},
            {0x120,"Good Bee Cave / Ice Cave"},
            //{0x120,"Ice Cave"},
            {0x121,"Blacksmiths Hut"},
            {0x122,"Fortune Teller (Dark) / Fortune Teller (Light)"},
            //{0x122,"Fortune Teller (Light)"},
            {0x123,"Mini Moldorm Cave"},
            {0x124,"50 Rupee Cave / Bonk Rock Cave"},
            //{0x124,"Bonk Rock Cave"},
            {0x125,"20 Rupee Cave / Dark Lake Hylia Ledge Spike Cave"},
            //{0x125,"Dark Lake Hylia Ledge Spike Cave"},
            {0x126,"Bonk Fairy / Checkerboard Cave"},
            //{0x126,"Checkerboard Cave"},
            {0x127,"Dark World Hammer Peg Cave"},

            /*
            { 0x00, "00 Link's house (middle spawn house)" },
            { 0x01, "01 Link's house (Door)" },
            { 0x02, "02 Sanctuary (Main Entrance)" },
            { 0x03, "03 Hyrule Castle (Left Entrance)" },
            { 0x04, "04 Hyrule Castle (Main Entrance)" },
            { 0x05, "05 Hyrule Castle (Right Entrance)" },
            { 0x06, "06 Old man cave (Lower Entrance)" },
            { 0x07, "07 Old man cave (DM Entrance)" },
            { 0x08, "08 Eastern Palace (Main Entrance)" },
            { 0x09, "09 Desert Palace (Main Entrance)" },
            { 0x0A, "0A Desert Palace (Right Entrance)" },
            { 0x0B, "0B Desert Palace (Left Entrance)" },
            { 0x0C, "0C Desert Palace (Boss Entrance)" },
            { 0x0D, "0D Kakariko double house (Left Entrance)" },
            { 0x0E, "0E Kakariko double house (Right Entrance)" },
            { 0x0F, "0F Angry brother house (Left Entrance)" },
            { 0x10, "10 Angry brother house (Right Entrance)" },
            { 0x11, "11 Smith Cave (Main Entrance)" },
            { 0x12, "12 Agahnim Tree Cave (Cave Entrance)" },
            { 0x13, "13 (DW)DMR Bottom Left (Cave Entrance)" },
            { 0x14, "14 (DW)DMR Top cave" },
            { 0x15, "15 (DW)Turtle Rock Laser eyes (Bomb Cave Entrance)" },
            { 0x16, "16 (DW)Bumper Cave Bottom Entrance (Cave Entrance)" },
            { 0x17, "17 (DW)Bumper Cave Top Entrance (Cave Entrance)" },
            { 0x18, "18 (DW)Turtle Rock Laser Skip (Bomb Cave Entrance)" },
            { 0x19, "19 (DW)Turtle Rock Big Chest (Cave Entrance)" },
            { 0x1A, "1A (LW)DMR Black rocks cave (Cave Entrance)" },
            { 0x1B, "1B (LW)DMR Middle cave via drop (Cave Entrance)" },
            { 0x1C, "1C (LW)DMR Spiral Cave (Cave Exit)" },
            { 0x1D, "1D (LW)DMR Spiral Cave via drop (Cave Entrance)" },
            { 0x1E, "1E (LW)DMR Bottom Right 2 Caves (Cave Entrance)" },
            { 0x1F, "1F (LW)DMR Bottom Right (Cave Entrance)" },
            { 0x20, "20 (LW)DMR Top Right (Cave Entrance)" },
            { 0x21, "21 (LW)DML Top Left via drop (kikiskip) (Cave Entrance)" },
            { 0x22, "22 (LW)DML Top Middle via drop (Cave Entrance)" },
            { 0x23, "23 (LW)DML Top Middle Spectacle rock (Cave Entrance)" },
            { 0x24, "24 (LW)Agahnim Tower" },
            { 0x25, "25 (DW)Swamp Palace" },
            { 0x26, "26 (DW)Palace Of Darkness" },
            { 0x27, "27 (DW)Misery Mire" },
            { 0x28, "28 (DW)Skull Woods (Entrance with Bumper / Key Pot)" },
            { 0x29, "29 (DW)Skull Woods (Statue Push Entrance)" },
            { 0x2A, "2A (DW)Skull Woods (Big Chest Entrance)" },
            { 0x2B, "2B (DW)Skull Woods (Boss part Entrance)" },
            { 0x2C, "2C (LW)Woods Heart Piece (Tree Entrance)" },
            { 0x2D, "2D (DW)Ice Palace Entrance" },
            { 0x2E, "2E (LW)6 holes cave exit of DM" },
            { 0x2F, "2F (LW)DML Long ladder cave" },
            { 0x30, "30 (LW)DML Old Man (healing) cave" },
            { 0x31, "31 (LW)DML Bottom Cave (old man exit)" },
            { 0x32, "32 (LW)Secret bush entrance (Door)" },
            { 0x33, "33 (LW)Tower of Hera" },
            { 0x34, "34 (DW)Thieves Town" },
            { 0x35, "35 (DW)Turtle Rock (Main Entrance)" },
            { 0x36, "36 (DW)Pyramid Entrance between 2 statue" },
            { 0x37, "37 (DW)Ganon's Tower" },
            { 0x38, "38 (LW)Right side of Cemetary (cave entrance)" },
            { 0x39, "39 (LW)Kakariko Well (Door)" },
            { 0x3A, "3A (DW)DMR Top Right (under rock)" },
            { 0x3B, "3B (DW)DMR Door leading to floating island" },
            { 0x3C, "3C (DW)SHOP" },
            { 0x3D, "3D (DW)Npc cave top right of swamp" },
            { 0x3E, "3E (LW)Kakariko Right House" },
            { 0x3F, "3F (LW)Kakariko Left House" },
            { 0x40, "40 (LW)Kakariko Sickboy house" },
            { 0x41, "41 (LW)DML Spike cave" },
            { 0x42, "42 (LW)Tavern Main Entrance" },
            { 0x43, "43 (LW)Tavern Back Entrance" },
            { 0x44, "44 (LW)Kakariko Bushes House" },
            { 0x45, "45 (LW)Sarahsrala's Hut" },
            { 0x46, "46 (LW)Kakariko SHOP" },
            { 0x47, "47 (DW)Chest Minigame" },
            { 0x48, "48 (DW)300 rupees,Redboom hut" },
            { 0x49, "49 (LW)Library" },
            { 0x4A, "4A (LW)Secret bombhouse Kakariko" },
            { 0x4B, "4B (LW)Chicken House" },
            { 0x4C, "4C (LW)Witch Potion Shop" },
            { 0x4D, "4D (LW)Desert Aginah Cave" },
            { 0x4E, "4E (LW)DAM Entrance" },
            { 0x4F, "4F (LW)DMR Mimic cave" },
            { 0x50, "50 (LW)DMR Fairyhookshot cave" },
            { 0x51, "51 (LW)Mirror cave under flute location" },
            { 0x52, "52 (LW)Cemetary Mirror Cave" },
            { 0x53, "53 (DW)Link's House Bomb shop" },
            { 0x54, "54 (DW)C-Shaped House Kakariko" },
            { 0x55, "55 (DW)FairyCave" },
            { 0x56, "56 (LW)Ice rod cave (Right cave)" },
            { 0x57, "57 (DW)Lonely Shop West of pyramid" },
            { 0x58, "58 (LW/DW)Cave SHOPS" },
            { 0x59, "59 (DW)Archery Game" },
            { 0x5A, "5A (DW)Sanctuary Cave" },
            { 0x5B, "5B (LW)Cape Grave Entrance" },
            { 0x5C, "5C (LW)Waterfall Pond" },
            { 0x5D, "5D (LW)Arrow/Bombs Pond" },
            { 0x5E, "5E  All Big Fairy Rooms" },
            { 0x5F, "5F (DW)Left Mire Entrance (2 chest)" },
            { 0x60, "60 (DW)SHOPS" },
            { 0x61, "61 (LW)Thieves Hut" },
            { 0x62, "62 (DW)Desert Cave" },
            { 0x63, "63 (DW)Pyramid Pond" },
            { 0x64, "64 (LW)Smith House" },
            { 0x65, "65 (LW)Fortune Teller" },
            { 0x66, "66 (DW)Fortune Teller" },
            { 0x67, "67 (LW?)3Chest minigame" },
            { 0x68, "68 (DW)MiniTree? House (Palace of darkness Area)" },
            { 0x69, "69 (DW)Flute #5 Cave" },
            { 0x6A, "6A (??)NPC Cave" },
            { 0x6B, "6B (LW)SHOP" },
            { 0x6C, "6C (LW)Minimoldorm cave hylia lake" },
            { 0x6D, "6D (LW)Thief Cave" },
            { 0x6E, "6E (LW)Sanctuary under rock cave" },
            { 0x6F, "6F (LW)Thief Cave near ice rod" },
            { 0x70, "70 (??)Unknow Spike cave" },
            { 0x71, "71 (LW)link's fairy cave" },
            { 0x72, "72 Desert mirror block maze" },
            { 0x73, "73 Zelda Cell (Spawn beside zelda) (intro entrance)" },
            { 0x74, "74 Hyrule Castle Throne Room (intro entrance)" },
            { 0x75, "75 Agahnim Torture Room (intro entrance)" },
            { 0x76, "76 Skull Woods big chest (Drop Entrance)" },
            { 0x77, "77 Skull Woods left hole (Drop Entrance)" },
            { 0x78, "78 Skull Woods right hole (Drop Entrance)" },
            { 0x79, "79 Skull Woods lost hole? (Drop Entrance)" },
            { 0x7A, "7A Forest Heart Piece middle bush (Drop Entrance)" },
            { 0x7B, "7B Ganon (Drop Entrance)" },
            { 0x7C, "7C bush right side of cemetary (Drop Entrance)" },
            { 0x7D, "7D Escape secret entrance bush (Drop Entrance)" },
            { 0x7E, "7E Smith powder (Drop Entrance)" },
            { 0x7F, "7F Lumberjack tree (Drop Entrance)" },
            { 0x80, "80 Kakariko Well (Drop Entrance)" },
            { 0x81, "81 Escape Grave (Drop Entrance)" },
            { 0x82, "82 Houlihan Cave (Drop Entrance)" },
            { 0x83, "83 Smith Pegs Cave" },
            { 0x84, "84 Ice Rod Cave (Left Entrance)" },
            */
        };
    }
}
